### ISSUE TITLE
Controller API's are different between Deck.gl and react-map-gl 

### ISSUE THREAD

**Issue by romaxa** [visgl/deck.gl#3066]
We've recently faced an issue with Deck.gl controller API which does not accept an instance of the extended controller. And introducing inconvenience of using global variables in order to connect Deck.gl hosting component and controller.

API for react-map-controller pointing to the creation  of controller instance:
https://uber.github.io/react-map-gl/#/Documentation/advanced/custom-map-controller

But deck.gl only allows specifying the class reference:
https://deck.gl/#/documentation/deckgl-api-reference/controllers/map-controller

Any reason why it is not allowed to pass the controller instance in Deck? and why these API's principals are different?

**Comment by ibgreen** [comment]
> Any reason why it is not allowed to pass the controller instance in Deck? 

The rest of the deck.gl API encourages you to create a new component each render. We support this under the hood by managing shared state for layer instances. But for controllers we haven't implemented this sharing, and if the user created a new Controller each turn, things would not work.

This is why we opted for the class instead of instance approach.

We could either support both. Or we could build on the breakout of `ComponentManager` from `LayerManager` and make `Controllers` inherit from `Component` which would make them compatible with the "reactive" programming pattern.

**Comment by romaxa** [comment]
can we pass context property into the controller and get it accessible in controller instance created by deck? within that context object we can share state as we want.
