### ISSUE TITLE
Blury images in Bitmap Layer

### ISSUE THREAD

**Issue by abinashpanda** [visgl/deck.gl#3372]
#### Description
Bitmap layer when combined with TileLayer renders blury images for raster tiles.

By using raster layer in mapbox-gl I am getting
![Screenshot 2019-07-25 at 12 12 48 AM](https://user-images.githubusercontent.com/2332955/61819634-0d593b80-ae71-11e9-94d2-b6d93951b8c5.png)

whereas by using TileLayer along with BitmapLayer I am getting 
![Screenshot 2019-07-25 at 12 12 41 AM](https://user-images.githubusercontent.com/2332955/61819664-1cd88480-ae71-11e9-8cdc-0acb186e381b.png)

Am I missing something?

Thanks in advance.

#### Repro Steps
- Expected Behaviour - https://codesandbox.io/s/loving-tharp-o1r7u (using mapbox-gl js)
- Actual Output - https://codesandbox.io/s/admiring-heyrovsky-p9r5y (using Deck.Gl)

#### Environment (please complete the following information):
 - Framework Version: [e.g. deck.gl 7.2.0alpha/7.0.1]
 - Browser Version: [e.g. Chrome 71.0]
 - OS: [e.g. Mac OS X 10.4]

**Comment by xintongxia** [comment]
@abinashpanda I am not able to see the result of your first sandbox codesandbox.io/s/loving-tharp-o1r7u

**Comment by kylebarron** [comment]
I was curious if this was still the case, since I was attempting my own fragment shader deriving from `BitmapLayer` and it seemed blurry. So I made a small example ([code](https://github.com/kylebarron/deckgl-bitmap-layer-blurry-example/blob/master/src/App.js), [website](https://kylebarron.dev/deckgl-bitmap-layer-blurry-example)) and found that BitmapLayer now renders essentially identically to Mapbox GL. The only differences are seen between zoom `x.0-x.5`, i.e. at zoom 12.3, because there Mapbox GL requests tiles at zoom 12, and the `TileLayer` requests at zoom 13.

So I think this issue can probably be closed, and my issue is in my shader code.

**Comment by kylebarron** [comment]
Actually I think I spoke too soon! When using 512px tiles, the rendering is indistinguishable, but with 256px tiles it looks like there is a difference! Let me update the example...

**Comment by kylebarron** [comment]
I'm not sure if these screenshots are clear; I think it's easier to toggle the rendering on the example ([code](https://github.com/kylebarron/deckgl-bitmap-layer-blurry-example/blob/master/src/App.js), [website](https://kylebarron.dev/deckgl-bitmap-layer-blurry-example)). It's subtle, but there's a distinct difference in sharpness, with Deck.gl less sharp with 256px tiles. @Pessimistress 

Deck.gl:
![image](https://user-images.githubusercontent.com/15164633/78598003-b4b5ad00-780b-11ea-8e03-dd8cf003bb1d.png)
React Map GL / Mapbox
![image](https://user-images.githubusercontent.com/15164633/78598038-c6975000-780b-11ea-82c0-186e5e51364c.png)

**Comment by ibgreen** [comment]
@kylebarron Maybe check in network tab what the two frameworks load at what time, see if there is a difference? 

I.e. narrow down if it is due to a rendering issue or down to tile loading decisions? Maybe mapbox always loads more "pixels" than is "needed" so that they always can match screen device pixels at least 1:1.

Disclaimer: I have not followed this issue in detail so ignore comments if I am off the mark...

**Comment by kylebarron** [comment]
No I think you're right...

Looking at the network requests, at zoom 14.0, Mapbox GL requests tiles at zoom 15. I think Mapbox detects I'm using a high res screen, but since I'm providing 256px tiles, Mapbox requests tiles at zoom `n+1`. With the `BitmapLayer`, at zoom 14.0 it requests tiles at zoom 14; at zoom 14.01-15.0 it requests tiles at zoom 15.

**Comment by kylebarron** [comment]
Closing as this should be solved with `TileLayer` improvements as of 8.1. Feel free to open a new issue if you still are having problems.
