### ISSUE TITLE
Loading Scenegraph layers from URLs which don't have the '.glb' extension

### ISSUE THREAD

**Issue by harrycollin** [visgl/deck.gl#3846]
Is there a way to load glb files from URLs which don't have the '.glb' extension?

**Comment by ibgreen** [comment]
@harrycollin Apologies for missing this question. I'll add a belated answer for reference.

> Is there a way to load glb files from URLs which don't have the '.glb' extension?

Yes. Apart from the more complicated approach of manually importing and calling the `GLTFLoader` from loaders.gl, there is also support for autodetecting loader from file contents and MIME types (in addition to file extensions).

If you control the serving of the file you could try the MIME type route, otherwise content detection should work in many cases.

However, based on the original title of this issue "Browser File Object to Scenegraph" it sounds like you are loading from a browser `File` object. 

Autodetecting from browser File object content is a new feature in the upcoming loaders.gl 2.3 version - currently available in alpha releases only. (The `File` case was a little trickier to support as reading initial bytes from a `File` object requires an asynchronous operation.)
