### ISSUE TITLE
Add onClick event listener in pydeck

### ISSUE THREAD

**Issue by pancho111203** [visgl/deck.gl#3864]
#### Target Use case
In my case I want to create an interactive map where you can select zones (postal codes) and the pandas dataframe with the data gets filtered to only show that zone in the map. I know about the r.deck_widget.selected_data attribute, but can't find the way to make the map react to changes to it.

#### Proposed feature
Ability to add event handlers to any layer, enabling two way communication from the map to the python environment.

**Comment by ajduberstein** [comment]
Thanks for the suggestion! I like the idea quite a bit--I'll have to think about how to support it given the current architecture. iI's not quite the experience you're describing but you can load your selected data into another map in a different notebook cell.

**Comment by kylebarron** [comment]
This is actually a quite simple addition I think, using Jupyter Widgets' event handlers. https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20Events.html#Traitlet-events

You can just pass a handler function to the widget's `observe` method:
```py
def handler(change):
    global selected_data
    selected_data = change
    
# you can select which traitlets keys it observes
r.deck_widget.observe(handler, ['selected_data'])
```

Then each time `selected_data` changes in Deck.gl, i.e. every time you click and the picking is updated, the `change`/`selected_data` object is a `dict` (technically a traitlets object that's `dict`-like) with 5 keys: 
```
['name', 'old', 'new', 'owner', 'type']
```

- `new`: for some reason this is empty?
- `old`: This is a full dict of `selected_data`
- `owner`: widget object. So you could just grab `selected_data` from the widget through this, and just use `observe` as an event to let you know when the data has changed?

So it would be possible to hook that up to a (Geo)DataFrame to keep a record of what was picked in Deck.gl. Especially with a (Geo)DataFrame since filtering the index is fast, you could have a handler like (pseudocode)
```py
def handler(change):
	# Get indices from change	
	data = change.owner.selected_data
	indices = [feature['id'] for feature in data]
	global selected_df
	selected_df = df.loc[indices]
```

**Comment by Pessimistress** [comment]
Supported in pydeck 0.5.
