### ISSUE TITLE
Disable dot radius scaling

### ISSUE THREAD

**Issue by ibesora** [visgl/deck.gl#3979]
#### Target Use case
Imagine wanting a scatter plot with dots of different radius that do not scale based on zoom.
The radius scaling can be disabled by setting the `radiusMinPixels` and `radiusMaxPixels` properties to the same value but that also limits the different radius that can be shown in the same layer.
The current way to do this would be to create a different `ScatterplotLayer` for each radius but this doesn't feel right.

For example, if we wanted to show three different radius sizes we would do the following:
```javascript
[ new ScatterplotLayer({
    ...
    getRadius: 7,
    radiusMinPixels: 7,
    radiusMaxPixels: 7,
    ...
  }),
  new ScatterplotLayer({
    ...
    getRadius: 14,
    radiusMinPixels: 14,
    radiusMaxPixels: 14,
    ...
  }),
  new ScatterplotLayer({
    ...
    getRadius: 21,
    radiusMinPixels: 21,
    radiusMaxPixels: 21,
    ...
  })]
```

#### Proposed feature
~~Having a `radiusScalingEnabled` boolean property would greatly reduce the layer complexity as we could do something like the following~~
Following the conversation with @ibgreen in [this same issue](https://github.com/uber/deck.gl/issues/3979#issuecomment-563342310) the proposed feature is to have a `radiusUnits` property (similar to the `sizeUnits` property found in [TextLayer](https://github.com/uber/deck.gl/blob/master/docs/layers/text-layer.md#sizeunits-string-optional) for example)
```javascript
[ new ScatterplotLayer({
   ...
    getRadius: (f) => { /* return 7, 14, or 21 depending on something */ },
    radiusUnits: 'pixels'
  })]
```~~

**Comment by ibgreen** [comment]
Many layers allow you to switch `units` from `meter` units to `pixel` which should do that you want...

For `ScatterplotLayer`, reading the docs/source, there is a `lineWidthUnits` prop that can be set to `'pixels'` instead of `'meters'`, but it doesn't sound like that controls the interpretation of the entire radius?

@Pessimistress @xintongxia

**Comment by ibesora** [comment]
> Many layers allow you to switch `units` from `meter` units to `pixel` which should do that you want...

Having the same value to `radiusMinPixels` and `radiusMaxPixels` disables the radius scaling but doing that doesn't support multiple fixed sizes on the same layer. Having different values of `radiusMinPixels` and `radiusMaxPixels` scales the dot radius while zomming in/out so while you can have multiple sizes in the same layer, the scaling is enabled. 
That's why I'm proposing a new `radiusScalingEnabled` property

**Comment by ibgreen** [comment]
> That's why I'm proposing a new radiusScalingEnabled property

Yes understood. 

I am just suggesting that if there was `units: 'pixels'` prop it should have the same effect as your proposed `radiusScalingEnabled` (i.e. `units` would affect the interpretation of the `getRadius` accessor's return value which is what lets you specify different radii for different "rows" in your `props.data` table). 

It would also be more consistent with the rest of the deck.gl Layers (many of which have `units` props, instead of adding a one-off extra prop for controlling the scatterplot radius prop).

**Comment by ibesora** [comment]
Oh! Now I understand what you are saying. I thought that having `radiusMinPixels` and `radiusMaxPixels`, radius was already in pixels.
Good call, much more cleaner than my proposal. Will edit the issue description to reflect your proposal.

**Comment by Pessimistress** [comment]
`radiusUnits: 'pixels'` is supported in 8.2
