### ISSUE TITLE
Potential Enhancements: only render picking buffer near mouse position, and avoid rendering picking buffer when mouse is scrubbing the canvas

### ISSUE THREAD

**Issue by lsb** [visgl/deck.gl#4109]
#### Target Use case

The picking stage of rendering is happening while the user is waiting to see feedback, so on heavier richer maps, this would increase the frame rate.

For 2, if the map has no new pickable layers and the viewport has not changed (no shift of perspective, no submenu in a popup), the cost of rendering a picking buffer could be avoided, and this could increase frame rate.

For 1, it seems that the most common picking workflow is to render the (subsampled?) screen to a texture, and look up a color near the cursor position. If the fragment shaders all received the mouse position and the radius of interest, and initially checked if their FragCoord is outside the circle around the cursor position, and discarded their fragment before doing any work, many fragment pixels would get discarded, potentially many from the same fragment at the same time, and this would increase frame rate.

#### Proposed feature

The goal of opening this issue is mostly to start a discussion around the feasibility and prudence of this feature, more than to start implementation.

Part 1, fragment shaders get a vec2 uniform of the x,y coordinates of the mouse (if they don't already) and a float uniform of a radius around that x,y coordinate, check if their gl_FragCoord is within that radius, and discard otherwise. This can be implemented incrementally for the heaviest layers first.

Part 2, the picking buffer gets its own flag for whether it requires redraw, and whenever the viewport stays the same and the pickable layers stay the same, the picking buffer is not dirtied and is reused.

Thanks for your time :slightly_smiling_face: I'm finding 10-15fps on my GTX 1070 when picking on 1.2M points and 200k text labels, so I've been happy with the performance even on an older system

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] What’s new update 
  - [ ] Test

**Comment by Pessimistress** [comment]
Thank you for writing this up. Here is the current state of picking and some areas of improvement we are considering:

We only render the 1x1 area under the pointer on hover:

https://github.com/uber/deck.gl/blob/412ef8a4d480497d3b4e02ede281e972e14ed0f3/modules/core/src/passes/pick-layers-pass.js#L44-L45

It's possible to cache the picking result at each coordinate to avoid re-rendering the picking buffer, although I'm not sure how much perf benefit that would bring (we would be caching sparse pixels on a very big canvas).

To further complicate things, we have the `autoHighlight` feature, which dirties the model as soon as a layer is picked (imagine a layer that makes circles bigger on hover.)

We indeed still need to draw all layers into this pixel, because deck has no knowledge of where each layer would draw. The idea of discarding fragments based on `gl_FragCoord` is interesting - definitely curious to see how it performs in a stress test. @tsherif

**Comment by lsb** [comment]
Ah, my mistake, thanks for the detailed explanation! I had thought the picking layer was a full-sized image, but single-pixel scissored renders makes sense.

My use case was a pretty heavy map (https://leebutterman.com/sister-cities-map) with 1.1M points, 0.5M text strings at 20 characters each, charset 500 or so, and I was seeing picking taking tens to hundreds of milliseconds when the GPU was active with other workloads (this picking time dropped to a few milliseconds for 15-20FPS when the GPU did not have a heavy workload).
