### ISSUE TITLE
Full examples from https://deck.gl/#/examples/overview?

### ISSUE THREAD

**Issue by bergkvist** [visgl/deck.gl#4138]
Is there a reason you wouldn't want to make the full example code available?

#### I find it a bit confusing that the "View Code"-link does not link to the actual code of the example. Instead, it links to a much simpler example
I understand that having minimal and simplified examples can be of great value for getting started with deck.gl. I think it is a bit misleading that the full examples link to only a simplified version.

![image](https://user-images.githubusercontent.com/410028/72213380-659efb00-34ee-11ea-8109-86f1923155e1.png)

In general, with larger data sets, certain optimizations can play a big role (which is not noticeable with small data sets). Understanding and playing around with these optimizations is something that would be really cool.

**Comment by bnping** [comment]
i can see this pb also.

**Comment by Pessimistress** [comment]
> I find it a bit confusing that the "View Code"-link does not link to the actual code of the example. 

They are the actual code. The website is literally compiled from these directories. I think you mean the data sample is smaller than what's shown on the website?

When running standalone, the examples load data samples from JSON/CSV format so that you can follow the URL and read the input. Some datasets used on the website are very large if encoded in JSON (>20M) and will take a long time to download, the only reason why we opt for a smaller sample.

If you are interested in compressing large datasets over the wire, you can look into tools such as [protobuf](https://developers.google.com/protocol-buffers), [flatgeobuf](https://github.com/bjornharrtell/flatgeobuf) etc. This is outside of the scope of deck.gl.
