### ISSUE TITLE
Chrome crashes with Terrain Layer with pitch > 60 'over fetching' tiles

### ISSUE THREAD

**Issue by mogmog** [visgl/deck.gl#4482]
If I use Terrain layer with a pitch of > 60 then the number of requests rockets as it fetches tiles for areas far in the distance on the horizon that dont need the same high res version as those tiles in the fore ground.

It ends up fetching over 100Mb on the St Helena demo and kills my browser tab.

If someone can give me some clues on a strategy I can attempt fixing this but might need some help.

**Comment by kylebarron** [comment]
I don't think there's a good way around this, and so I would suggest when using the terrain layer to not increase the pitch past 60 degrees.

The reason is that the terrain layer combines heightmaps and image textures using the normal OSM tile index. That means that there's no way to have an approximate outline of the terrain in the distance without downloading and creating a mesh for every one of those tiles.

I believe this is something that other 3D formats, like `Tiles3D` and `I3S` fix... That you can quickly get a rough outline of the terrain without needing to build a mesh from scratch. The downside, of course, to those formats, is that you have to generate all the data in advance. One of the great benefits of the heightmap + image texture is that you can use any image texture without needing to do expensive and large data generation ahead of time.

One possible speedup improvement is to reduce the `meshMaxError` for tiles further away from the viewport. This might help the crashing, because a lower `meshMaxError` creates fewer triangles in the mesh, and would use less GPU memory. However this wouldn't do much to improve the _speed_ of the rendering, since the last step of creating a mesh, which is when `meshMaxError` is applied, is actually very fast anyways.

The other possible improvement, which would be more invasive, would be to _change the zoom level_ for fetching tiles far away. See this image from [a Mapbox GL JS PR](https://github.com/mapbox/mapbox-gl-js/pull/8975):
![](https://user-images.githubusercontent.com/55925868/68768333-fc545600-062a-11ea-8ba8-8a394c5ec0e2.png)
The tiles further away use data from lower zooms, which means fewer tiles to download and process.

**Comment by mogmog** [comment]
I know what you mean about it being more invasive - typically I like the fact that with Deckgl you have control of a lot of the parameters that are not always available to you with other libraries... but considering there is literally zero benefit to having full res tiles displaying on the horizon, changing the zoom level for tiles far away seems reasonable - pretty sure that's how all other libraries do it?

**Comment by mogmog** [comment]
Also, the idea of " when using the terrain layer to not increase the pitch past 60 degrees:" seems pretty dodge - how is a dev meant to know this?

**Comment by kylebarron** [comment]
> pretty sure that's how all other libraries do it?

What other libraries? Google Earth? ESRI? They have specialized tile formats that allow loading less data further away. If you want highest performance at high pitch, then generate your own 3DTiles or I3S tiles.

Mapbox? No, Mapbox GL JS is 6 years old and they just implemented this a couple months ago, and it's not even used in a release yet.

> Also, the idea of " when using the terrain layer to not increase the pitch past 60 degrees:" seems pretty dodge - how is a dev meant to know this?

Because the default max pitch is 60, as it is in Mapbox GL JS. You can't increase the pitch beyond that unless you manually change the parameters to `MapView`. If you change those parameters you need to accept the performance implications.

> but considering there is literally zero benefit to having full res tiles displaying on the horizon, changing the zoom level for tiles far away seems reasonable

Overall, be my guest. I'd be happy to see a PR for this, but I think it's not simple.

**Comment by mogmog** [comment]
It's ESRI and Cesium that I have familiarity with - and yeah I know what you mean they seem to have specialised formats rather than relying on 'vanilla' DEM files.

I am now experimenting with ESRI and deck layers together so that might be a work around

**Comment by kylebarron** [comment]
Well if you can access 3DTiles/I3S tiles through their API, you can just use the 3D Tiles module/layer

**Comment by ibgreen** [comment]
Some history: From the deck.gl side, we have been lobbying mapbox for a long time (since 2016, I just checked the ticket!) to add for support [pitch > 60](https://github.com/mapbox/mapbox-gl-js/issues/3731), and my understanding is that the same "infinite amount of tiles at the horizon issue" is also the reason that they did not supported it.

Now that deck.gl has a growing set of tile layers, we are starting to hit the same technical limitation as mapbox did. 

My expectation is certainly that deck.gl will overcome this limitation. And indeed there are a number of things we can do, most of them mentioned above:
- avoid loading tiles a certain distance from the horizon (just show a background color, or repeat last tile, or render nothing, or a grid, or ...).
- only load tiles that are bigger than a certain size in pixels.
- load lower zoom tiles for pixels close to the horizon.
- Use a request scheduler (presumably the one from the Tile3DLoader).
- etc.

In the mean-time, assuming this issue is just related to showing tile layers close to pitch 0 (i.e. not from underneath) you could just add code that hides the terrain layer while the pitch is close to the horizon (+30 to -30 degrees). This should allow avoid the crash and allow the user to "get under" the terrain.

**Comment by mogmog** [comment]
Hiding the tiles close to the horizon- It introduces a possibility of creating an Deckgl Effect that performs a fog/blur just at the horizon - in order to smooth it out.

**Comment by MacieJCzarkowskI** [comment]
@ibgreen Is there any request scheduler for layers? I have geoserver WMTS request and when pitch is more than 60 i get hundreds of them.

**Comment by ibgreen** [comment]
Not in the layers, but there is indeed a request scheduler in loaders.gl, in the [`@loaders.gl/loader-utils` ](https://github.com/visgl/loaders.gl/tree/master/modules/loader-utils/src/lib/request-utils) module. 

At the moment that implementation is rather hacky, it was put together quickly to improve 3D tile loading, however the idea is to clean it up and also use it for 2D tiles. 

So there is a plan (or at least an intent), but obviously someone needs to do the actual work. FWIW, it currently looks like my team will be looking at that within the next month or so as part of a project we are working on.

@kylebarron

**Comment by Pessimistress** [comment]
@MacieJCzarkowskI The over requesting issue is not going to be solved with a request scheduler. We need to not request those tiles at all. This can be fixed with frustum culling and dynamic LOD, which I'm looking into now.

**Comment by Pessimistress** [comment]
This will be fixed in the upcoming 8.2.0 release. You can try it now with `8.2.0-beta.1`.

**Comment by nwakkaf** [comment]
Is this already solved by Here maps: https://developer.here.com/documentation/examples/maps-js? using Alt key, we can have a flat view (also in 3d)
Actually I am wondering whether there is a possibility to use this service provided by Here along with the react version of deckgl, would be nice if somebody can suggest an idea.
