### ISSUE TITLE
Custom layers for pydeck partially broken in Jupyter environment

### ISSUE THREAD

**Issue by ajduberstein** [visgl/deck.gl#4506]
#### Description

Custom layers don’t load properly via Deck.show() in Jupyter Notebook environments in pydeck 0.3.

#### Environment (please complete the following information):
 - Framework Version: [e.g. deck.gl 6.3.0] pydeck 0.3, deck 8.2-alpha.1
 - Browser Version: [e.g. Chrome 71.0] 
 - OS: [e.g. Mac OS X 10.4]

**Comment by heshan0131** [comment]
your custom layer bundle is umd, it is not going to work in notebook's requireJS env. have you tried building it with rollup as `iife`?

i made a bundle with rollup and it works

```
import resolve from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import json from '@rollup/plugin-json';

const config = {
  input: 'src/bundle.js',
  output: {
    file: 'dist/bundle.js',
    format: 'iife',
    name: 'customLayerLibrary',
    globals: {
      '@deck.gl/core': 'deck',
      '@deck.gl/layers': 'deck',
      '@luma.gl/core': 'luma'
    }
  },
  external: ['@deck.gl/core', '@deck.gl/layers', '@luma.gl/core'],
  plugins: [
    resolve({
      browser: true,
      preferBuiltins: flase
    }),
    commonjs()
  ]
};

export default config;

```

**Comment by ajduberstein** [comment]
This works for Notebook but doesn’t seem to work with JupyterLab. Any ideas that support both?

**Comment by ibgreen** [comment]
Do we understand why it doesn't work?

Since we are implementing the script loading for the custom layer modules independently of the jupyter widgets `require` system etc, I don't quite understand why it would work on one system and not on another...

**Comment by kylebarron** [comment]
More concretely, does anyone know of links to Jupyter documentation detailing which bundling system is supported per project?

**Comment by heshan0131** [comment]
I don't understand why a iife module won't work for Labs. the problem @kyle encountered is because the layer module is expecting deck.gl to be defined as global, which is a valid expectation. pydeck widget should handle making deck available on global in both platforms.

Exactly like you said. jupyter notebook uses requireJS to pre bundle all scripts, which makes dynamically loading a umd module, register to requireJS and immediately execute it impossible. also the CustomLayer bundle depends on deck, which is bundled inside the pydeck jupyter widge 

I think to solve the problem pydeck should make deck available as a global in jupyterLabs

**Comment by ajduberstein** [comment]
Thank you @heshan0131–treating the deck bundle as a webpack external and a global solved the issue. No changes in pydeck necessary, just changes in the examples.

I've modified the example repo ([commit here](https://github.com/ajduberstein/pydeck_custom_layer/commit/f6fd950cf45e40535e78c15cfe08500ad8b5b64f)). [A working Notebook example is here](https://mybinder.org/v2/gh/ajduberstein/widget-bug/master?filepath=CustomLayer%20Example.ipynb). [A working Lab example is here](https://mybinder.org/v2/gh/ajduberstein/widget-bug/master?urlpath=lab).

Closing this out. Feel free to re-open if you think there are further changes to be made.
