### ISSUE TITLE
Deck.gl canvas width and height doubles/halves on layer rendering.

### ISSUE THREAD

**Issue by CaptainMack** [visgl/deck.gl#4561]
#### Description

Each time my layers a rerendered due to data changes, the canvas width and height doubles/halves, e.g. see [a clip of it](https://www.dropbox.com/s/yfu3cstx0nct7m2/width%20%2B%20height%20doubles.mov?dl=0)

I can see that my layers jump to the right most corner and back. However, after a while, it seems to normalize and keep the width/height constant. However, resizing the browser window does not resize the canvas causing visualisation to become offset to the map, but this might be an entirely other problem.

The expected behaviour is to keep width and height constant since Deck v.5.2.0 (see early issue here: https://github.com/visgl/deck.gl/issues/1687) 

#### Environment (please complete the following information):
 - Framework Version: 8.1.3
 - Browser Version: Chrome 81
 - OS: MacOS Catalina 10.15 (Retina)

#### Logs
No warnings, only info about layers being re-rendered.

**Comment by Pessimistress** [comment]
Can you create an example that reproduces this?

**Comment by CaptainMack** [comment]
Sure, as the system is somewhat complex, I've pushed the code to https://alpha.cityflow.live

I have done a bit more research into this, and it seems like it is primarily on the MacBook Retina. Deploying Chrome to e.g. a external screen does not recreate this jumping every second layer refresh

**Comment by CaptainMack** [comment]
You can use the login:

User: test@test.com
Pass: test

**Comment by Pessimistress** [comment]
I am unable to reproduce the issue (I don't have a MacBook). However, I can offer some general advice.

I assume you are setting Deck's `width` and `height` to `100%`, which makes its size relative to the offset parent.

Your canvas' offset parent appears to be `document.body`, with the styles `position: absolute; width: 100%; height: 100%`. As you add/remove/restyle child nodes in the document, its size may change, and subsequently changing the meaning of `100%`. The behavior subjects to the dynamics of your app and the browser/device at runtime. It is generally favorable to use absolute values to define the size of the layout root, for example `width: 100vw; height: 100vh`, which has no ambiguity, providing a stable anchor for all the relatively sized descendants.

**Comment by CaptainMack** [comment]
Thank you for your time @Pessimistress - I've updated the CSS according to your recommendation, but I still do not believe that it is due to the CSS - it is the canvas width and height being set to 2X, whilst the styles/CSS is correct resolution. See the screenshot for how it actually looks with inspector on a retina screen:

![Screenshot 2020-05-22 11 05 33](https://user-images.githubusercontent.com/812080/82651267-362a9880-9c1c-11ea-86f7-d454f2644746.png)

However, we cannot resize the window, as the Deck.gl overlay will have a constant width and height, I do not know if this is also a symptom of something wrong or simply another issue.

Again, thank you for helping out!

**Comment by CaptainMack** [comment]
Actually, it's a mix as far as I can see now - the absolute width and height is the problem for both issues - if we manually set the values to 100vh and 100vw, then it scales correctly and maintains correct resolution. These values are of course overridden, when it re-renders.

**Comment by CaptainMack** [comment]
We've solved it using the following:

width and height set to 100vw and 100vh when instantiating deck.gl, alongside setting it in the CSS. Also, setting useDevicePixels to false solves both issues.

Thank you!

**Comment by enodr** [comment]
Hi,

I am experiencing the exact same problem on a macbook with retina display. I think the problem is here:
https://github.com/visgl/deck.gl/blob/master/modules/core/src/lib/deck.js#L477

Because clientWidth seems to be double from the width in the CSS style, there might be a bug here.
I am not expert how px relates to real size on a retina display but there seem to be quirk.
https://www.danrodney.com/blog/retina-web-graphics-explained-1x-versus-2x-low-res-versus-hi-res/

Here are the logs from onResize callback just after instantiating the component (btw using VueJS also with @deck.gl/core, not react component):

<img width="454" alt="Capture d’écran 2020-11-23 à 23 05 21" src="https://user-images.githubusercontent.com/10436257/100020649-742d9280-2de0-11eb-8cf4-7f0a3594041c.png">

And the element with width value double from pixel size in styling:

<img width="880" alt="Capture d’écran 2020-11-23 à 23 05 43" src="https://user-images.githubusercontent.com/10436257/100020646-7263cf00-2de0-11eb-8687-8b90c938a16f.png">
