### ISSUE TITLE
Dynamically overlaying layers through a control box 

### ISSUE THREAD

**Issue by DoParkEQ** [visgl/deck.gl#4565]
<img width="1792" alt="Screen Shot 2020-05-05 at 10 16 32 AM" src="https://user-images.githubusercontent.com/59836949/81076302-80401a00-8eb9-11ea-9bd9-d90b513286aa.png">

I am building a basic visualization system that layers can be toggled from the control box. 
I have `layers` that merge individual layers into one.

`const [layers, setLayers] = useState([densityLayer, pedestrianLayer]);`

I have `filterState` that tracks the activity in the control box. It contains the layer object as a property of `linkTo`

```
 const [filterState, setFilterState] = useState([
        {
          id: 'densityFilter',
          checked: true,
          description: 'Population density',
          linkedTo: densityLayer
        },
        {
          id: 'pedestrianFilter',      
          checked: true,
          description: 'Pedestrian volume',
          linkedTo: pedestrianLayer
        }
      ]);
```
and everytime `checked` property in `filterState` gets updated, it will launch `renderLayers()`
which will select corresponding layers whose `checked` property is `true`.
```
  useEffect(()=>{
        renderLayers();
      },[filterState]);

      const renderLayers = () => {
        const newLayers = []; 
        filterState.map(filter => (filter.checked && newLayers.push(filter.linkedTo)));
        setLayers(newLayers);
      }
```
Then `layers` is passed to DeckGL component as a `layer` prop. 

```
   <DeckGL
        initialViewState={viewState}
        controller={true}
        layers={layers}
      >
```
In the program turning off the layers works fine, but they do not turn back on. In the console, I noticed that the lifecycles between layers are different. Is there anything incorrect about my approach?

**Comment by Pessimistress** [comment]
Removed layers cannot be "recycled" like this. The recommended practice when using React is to create a new layer instance on every re-render, see https://deck.gl/#/documentation/developer-guide/using-layers?section=faq

If your user would toggle layers frequently, it is also recommended to set the `visible` prop instead of removing the layer, as explained in https://deck.gl/#/documentation/developer-guide/performance-optimization?section=favor-layer-visibility-over-addition-and-removal
