### ISSUE TITLE
TileLayer does not update accesors when passing new updateTriggers

### ISSUE THREAD

**Issue by juandjara** [visgl/deck.gl#4608]
#### Description

I'll explain this bug with an example:
I have a layer of polygons, and I'm using MVTLayer from @jesusbotella to render them.
I have a feature in my app where you can click a polygon to highlight it. In order to do this I've setup a `getFillColor` accessor in the layer to read from an external variable and some `onClick` and `updateTriggers` for that too. When I click a polygon I update the `updateTriggers` in the layer. The desired behaviour here is that layers will be re-drawn and `getFillColor` would be called again in that moment, but this is not happening. This only happens when new tiles are requested.

On the other hand, I've been reading Deck.gl code and I've found that the `TileLayer` class keeps a cache of current sublayers stored inside every tile (in TileLayer's `state`). This seems counter-intiutive to me, because of the declarative approach in the docs and the re-creating the layer instances at every update that happen at the top-layer level.

That being said, I think that changing the check on line 77 of `TileLayer` from `changeFlags.propsChanged` to `changeFlags.propsChanged || changeFlags.updateTriggersChanged` will solve the issue

#### Repro Steps

https://codepen.io/juandjara/pen/YzyBRjv
Try clicking a polygon. It should change its color, but it doesn't do that until you zoom in / out

#### Environment (please complete the following information):
 - Framework Version: [deck.gl 8.1.7]
 - Browser Version: [Firefox 76.0.1]
 - OS: [Mac OS X 10.15.1, 2017 13-inch MacBook]

#### Logs

There are no logs associated

**Comment by jesusbotella** [comment]
Hi @juandjara! Thanks for the research.

I have seen your CodePen example and it's true that layers are not updated whenever updateTriggers change due to caching. TileLayer will need to wipe the current cached layers when updateTrigger variables are updated.

I think you can open a new pull request applying that change if you want.

That said, if you want to highlight a single polygon on your map, there's a property named `highlightedFeatureId` in a pending PR that will allow you to highlight a single feature by its ID using MVTLayer.

https://github.com/visgl/deck.gl/blob/99a94f4ae03803772be58a8656219619bb2a93ba/docs/layers/mvt-layer.md#highlightedfeatureid-number.

**Comment by juandjara** [comment]
Here is the PR: #4609

**Comment by Pessimistress** [comment]
Published 8.1.9
