### ISSUE TITLE
why escape the first newline character in most shader string literals ?

### ISSUE THREAD

**Issue by jonenst** [visgl/deck.gl#4864]
Hi,
browsing the source code, I see that most shaders are defined with
```
export default `\
...shadercode
`;
```

Why is there a backslash before the first newline in this multiline template string ?

ps1: "./modules/layers/src/bitmap-layer/bitmap-layer-vertex.js" and "./modules/layers/src/bitmap-layer/bitmap-layer-fragment.js" is the only one that doesn't have it.
ps2: "modules/geo-layers/src/trips-layer/trips-layer.js" and "modules/core/src/effects/post-process-effect.js" also use it for small shaders defined in the mail js file; All other small shaders in their main js files don't have it.
ps3: I would have asked this question on a mailing list or public chatroom but couldn't find one on the site or this repo's README

**Comment by ibgreen** [comment]
for shaders setting the GLSL `#version` that line must be start on the very first character otherwise the shader will not work.

For other shaders it is just a matter of discipline, avoiding spurious newlines at the beginning of shaders.

To join the slack channel go https://deck.gl/ and click search in the header and search for "slack".

**Comment by jonenst** [comment]
Thanks, sorry for the noise !
