### ISSUE TITLE
RFC: Style Classifier

### ISSUE THREAD

**Issue by alasarr** [visgl/deck.gl#4933]
#### Target Use case
Allow an easy way to style tile layers using tilestats.

If you need to style a TileLayer and you don't have access to all the data, you need to use stats to style the layer. 

Related with: https://github.com/visgl/deck.gl/issues/4930

#### Proposed feature
This RFC proposes the creation of a new utility class Classifier, to ease the styling of the layer's features, by working with its stats.

Having a way to create more easily styles for a layer could be achieved, by having a class to compute **bins with different classification methods**. Those bins could be used inside *style functions* returning colors or sizes, such as `getFillColor`. That class should be fed with metadata coming from the layer's source (or entered by the user).

Usage example:
```js
const colors = [
  [0, 0, 0, 0],
  [0, 255, 0, 0],
  [255, 0, 255, 0]
];

let classifier;

const layer = new MVTLayer({
  getFillColor: (f) => {
    const bin = classifier.getBin(f.population);
    return colors[bin];
	},
  onMetadata: (tilejson) => {
    const layerStats = tilejson.tilestats.layers[0];
    classifier = new Classifier({
      layerStats, // it could be eg. this.state.metadata.tilestats.layer[0]
      attribute: 'revenue', 
      method: 'quantiles', 
      bins: 3
    });
  }
});
```

Classifier params:
- **layerStats** : stats for the layer. The structure is defined by a layer item at the layers array of [Mapbox tilestats](https://github.com/mapbox/mapbox-geostats#output-the-stats). 
- **attribute**: attribute you want to use for the classifier
- **method**: 'quantiles', 'equal', 'jenk', 'stdev',
- **bins**: number of bins.

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] What’s new update 
  - [ ] Test

**Comment by kylebarron** [comment]
Can you give reasons why this should live in deck.gl?

In contrast to TileJSON, which is widely adopted, my understanding is that Mapbox's tile stats format is essentially an internal, private format they use for extra metadata after running Tippecanoe. If you upload a tileset to Mapbox, the public TileJSON endpoint they provide you doesn't contain these tile stats. Since tile stats isn't mentioned in the TileJSON spec, most third-party implementations won't include these statistics.

**Comment by alasarr** [comment]
The main issue is that there is no clear standard in the industry for tile stats. The closest option for a standard I know is Mapbox Tilestats. So I agree 100% it's no so direct as TileJSON.

Why I consider it could be in deck.gl? 

* There is no easy and common solution to style layers using bins. And it's a very common styling feature. This problem gets more complicated with tile layers where the user has no access to the full data. 

*  If someone needs to visualize a large layer, a very common solution is to "tilefy" the layer (and it will probably use Tippecanoe or a tool which uses Tippecanoe under the hood), so they already have this format of stats.

* You can use that for other layers too. You can calculate the stats in a GeoJSON layer and after that, you have an easy way for styling. 

If we would have a tile stats standard it'd be pretty obvious, but as it's not there we have the following options:
a) Move forward with something is not 100% standard but a common use case for the users.
b) Try to push around the standard to include tile stats at TileJSON.
c) a + b.

To be honest, after @kylebarron I'm not 100% sure what it's the best option. Thoughts?

**Comment by ibgreen** [comment]
This is just some quick thoughts.

As I understand it, 
- we want to be able to associate to each layer a "schema" containing a list of attributes `{name: string; type: 'string' | 'number' | ..., ....}`. 
- And then apply dynamic styling based on that schema. 
- And initialize that schema from tippecanoe generated tilejsons.

Regarding stats being non-standard... perhaps one could strike a reasonable balance by defining a more "generic" schema structure and add some code that knows how to convert the mapbox tileset stats into that structure. This way we wouldn't lock ourselves too tightly into the non-standard mapbox format, but still benefit from interoperability with a de-facto ecosystem. 

But a big problem is how to define that alternate schema format in a sufficiently general way based on only a single example format. There are some ideas in loaders.gl but it seems too early and cumbersome to impose alignment.

The styling API is also an interesting topic that could become a big project:
- One could choose to maximize interoperability with something like `d3` `d3.colorScale` etc rather than rolling now classes.
- We could try to use something like the Cesium 3D tiles styling language, which we need to finish implementing anyway for the 3D tiles module in loaders.gl
- We could build our own styling classes that could optionally allow for GPU acceleration.

But I don't want to slow this down, from my perspective a custom (composite?) layer subclass that implemented the proposed tile stats and classifier API would be acceptable as a first step, we can then evaluate and decide if we can generalize and move this support into the base layers.

**Comment by alasarr** [comment]
I've thought several times to create a bigger proposal, but I preferred to start with something small. 

What makes sense for me if to start bringing TileJSON support to TileLayer (#4930) and after that create a quick prototype to see how a style classifier looks like with your proposal of a more generic schema.

**Comment by Pessimistress** [comment]
Replaced by #5222
