### ISSUE TITLE
Select styles to icons on iconlayer.

### ISSUE THREAD

**Issue by phyopwint1912** [visgl/deck.gl#4960]
Hi guys, is there any way to add CSS styles or other styling method upon clicking the icon. I would like to add some border around the selected icon. 

```
const iconLayer = new IconLayer({
    id: 'icon-layer',
    data: data,
    pickable: true,
    iconMapping: ICON_MAPPING,
    coordinateSystem: COORDINATE_SYSTEM.METER_OFFSETS,
    getIcon: d => ({
        url: d.icon,
        width: 64,
        height: 64
    }),
    sizeMinPixels: 64,
    sizeMaxPixels: 64,
    sizeScale: 0.5,
    getPosition: d => d.coordinates,
    onClick: (info, e) => { handleOnClick(info, e) }
});

  const handleOnClick= (info, e) => {
    // Add styling here
  };
```

**Edited**
```
const handleOnClick = (info, e) => {
       setCustomLayer(

          new ScatterplotLayer({
            id: 'scatterplot-layer',
            data: info,
            pickable: true,
            opacity: 0.8,
            stroked: true,
            filled: true,
            radiusScale: 6,
            radiusMinPixels: 1,
            radiusMaxPixels: 100,
            lineWidthMinPixels: 1,
            getPosition: info.coordinate,
            getRadius: d => 10,
            getFillColor: d => [255, 140, 0],
            getLineColor: d => [0, 0, 0]
          })

        );
  };
```
So I was trying to add another layer on top of the icon, I was using ScatterplotLayer but things are not showing up and I wanted to have a rectangle stroke around the icon. Is anyone has idea how can I achieve that behavior. Thank you.

**Comment by Pessimistress** [comment]
You cannot pass [pickingInfo](https://deck.gl/docs/developer-guide/interactivity#the-picking-info-object) directly to the `data` prop because it is not an array. If you are not sure what it is try console.log it.

Icons are rendered in WebGL and are not DOM objects, you cannot apply CSS styles to them. You can either change the selected object to use a different icon, or add another layer that contains the stroke.
