### ISSUE TITLE
GeoJsonLayer unable to correctly render inverted polygons

### ISSUE THREAD

**Issue by austintang** [visgl/deck.gl#4981]
#### Description
When using deck.gl's GeoJsonLayer to render inverted polygons, the polygon fill isn't filling the correct areas as shown below:
![Screen Shot 2020-09-29 at 6 28 31 PM](https://user-images.githubusercontent.com/42187119/94633260-a360d100-0281-11eb-9e33-c620cd6ede86.png)

Sometimes, it gets rendered like the following:
![Screen Shot 2020-09-29 at 6 03 46 PM](https://user-images.githubusercontent.com/42187119/94634264-6cd88580-0284-11eb-94ac-1c0b250b2001.png)

This polygon is supposed to look like the following:
![Screen Shot 2020-09-29 at 6 19 32 PM](https://user-images.githubusercontent.com/42187119/94632773-5defd400-0280-11eb-8319-c1957855a3ed.png)

Here's a code sandbox link that uses deck.gl version 8.2.8 to render this polygon: https://codesandbox.io/s/busy-bush-i26xk

#### Repro Steps

This is the polygon I used in the provided screenshots and code sandbox example:
```
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [-180, 90],
            [-180, -90],
            [180, -90],
            [180, 90],
            [-180, 90]
          ],
          [
            [-130.34075330381458, -46.578067977728544],
            [-130.34075330381458, -11.381243740150515],
            [-83.84369617043481, -11.381243740150515],
            [-83.84369617043481, 68.1187524769574],
            [38.84308216077213, 68.1187524769574],
            [38.84308216077213, -8.409520695055782],
            [74.16819133795593, -8.409520695055784],
            [74.16819133795593, -47.413939624455544],
            [6.847682032685137, -47.413939624455544],
            [6.847682032685137, -21.700176371949645],
            [-64.393210082763, -21.700176371949645],
            [-64.393210082763, -46.578067977728544],
            [-130.34075330381458, -46.578067977728544]
          ],
          [
            [-57.127017448389985, 4.187255467457538],
            [-57.127017448389985,57.07804597371622],
            [5.109123348433257, 57.07804597371622],
            [5.109123348433257, 4.187255467457538],
            [-57.127017448389985, 4.187255467457538]
          ]
        ]
      }
    }
  ]
}
```

#### Environment (please complete the following information):
 - Framework Version: deck.gl 8.2.8
 - Browser Version: Chrome 85.0.4183.121
 - OS: Mac OS X 10.15.6

**Comment by Pessimistress** [comment]
There are two issues:

- [Web Mercator projection](https://en.wikipedia.org/wiki/Web_Mercator_projection) projects latitude=90 to infinity. If you change 90/-90 to 89/-89 it will render. Since this is valid GeoJSON, I agree that this is a bug in the layer.
- [earcut](https://github.com/mapbox/earcut) does not seem to handle hole inside of a hole. The GeoJSON specification does not specify how overlapping holes should be treated (either even-odd or non-zero); see [this issue](https://github.com/mapnik/mapnik/issues/3953#issuecomment-408539651) which claims that such geometry is invalid. This can be easily fixed by separating the "island" into its own feature.
