### ISSUE TITLE
Question about transparency between layers

### ISSUE THREAD

**Issue by liubx** [visgl/deck.gl#5034]
HI, I am using PolygonLayer and ScenegraphLayer to draw an indoor map. I have question about the transparency between layer. There are two cases. 

1. When I drew the ScenegraphLayer first. I can see the cabinet(ScenegraphLayer with 0.1 opacity) through the wall (PolygonLayer with 0.1 opacity), but I am not able to see the cabinet(ScenegraphLayer) and the wall(PolygonLayer with 0.1 opacity) through the fence(ScenegraphLayer with 0.1 opacity). 
<img width="717" alt="Screen Shot 2020-10-15 at 2 09 05 PM" src="https://user-images.githubusercontent.com/7749950/96083931-bc5bba00-0ef0-11eb-9d0c-134537cc2ab4.png">

2. When I drew the PolygonLayer first. I can see the wall(PolygonLayer with 0.1 opacity) through the fence(ScenegraphLayer with 0.1 opacity), but I am not able to see the cabinet(ScenegraphLayer) neither through the fence(ScenegraphLayer with 0.1 opacity) nor through the wall(PolygonLayer with 0.1 opacity). 
<img width="792" alt="Screen Shot 2020-10-15 at 2 07 21 PM" src="https://user-images.githubusercontent.com/7749950/96084014-e7dea480-0ef0-11eb-82f8-8f077805ca2b.png">

I think a more reasonable result should be the one where you can see any layers through a transparent layer. Is this a bug or what can I do to make it right? Thanks.

**Comment by Pessimistress** [comment]
By default, `depthTest` is enabled, which discards anything that's behind a rendered fragment. This means that if you have a translucent surface and an opaque surface:

- Translucent surface is closer to the camera, renders first -> you can't see through it
- Translucent surface is closer to the camera, renders last -> you can see through it (expected behavior)
- Opaque surface is closer to the camera, renders first  -> you can't see through it (expected behavior)
- Opaque surface is closer to the camera, renders last  -> you can't see through it (expected behavior)

Unlike game engines, deck.gl does not reorder geometries based on their distance during rerender. This is an intentional tradeoff between visual quality and performance.

A simple solution for your problem is to split the scenegraph into multiple layers, e.g. one for cabinets, one for fences. And order your layers so that "see-through" elements are rendered last.

**Comment by liubx** [comment]
Thank you for the explanation!

**Comment by liubx** [comment]
Is that means it is impossible for two translucent surfaces to see through each other? @Pessimistress

**Comment by Pessimistress** [comment]
You can disable the `depthMask` parameter when drawing the translucent layer. Surfaces drawn in this mode will not block others even if they are in front. See demo: https://codepen.io/Pessimistress/pen/LYZNveZ?editors=1010

This is not very precise (the result of color blending may still depend on the order drawn) but you'll be able to see through all the translucent geometries.

**Comment by liubx** [comment]
Ok, Thank you for your help!
