### ISSUE TITLE
pydeck in a separate repo

### ISSUE THREAD

**Issue by davidbrochart** [visgl/deck.gl#5068]
Is there any reason for `pydeck` to be part of the `deck.gl` GitHub repository? Usually, Jupyter widgets wrap a JS library but are completely separate from it (e.g. `ipyleaflet`/`leaflet`).

**Comment by ibgreen** [comment]
@davidbrochart Thanks for your feedback.

We are currently inspired by Apache Arrow  https://github.com/apache/arrow - where all language bindings are in one repo. 

Since most features in pydeck require changes both on JS side and Python side, there is a lot of overhead to having to make two separate PRs (one in deck and one in a separate Python repo).

It is of course nice to have Python specific issue list. Is that what you were hoping for?

(PS - We do have a separate pydeck repo but we only use it to publish the docs https://github.com/UnfoldedInc/pydeck)

**Comment by davidbrochart** [comment]
Thanks @ibgreen for your answer.

> Since most features in pydeck require changes both on JS side and Python side, there is a lot of overhead to having to make two separate PRs (one in deck and one in a separate Python repo).

It makes sense.

> It is of course nice to have Python specific issue list. Is that what you were hoping for?

No, I was not aware that changes had to be made in Python and in JS. I think I will understand more when I contribute. Looking forward to it!
