### ISSUE TITLE
Changing polygon fill faster

### ISSUE THREAD

**Issue by ibesora** [visgl/deck.gl#5077]
I have a performance issue about deck.gl that I want to see if it can be improved.

I'm using a [GoogleMapsOverlay](https://github.com/visgl/deck.gl/blob/master/docs/api-reference/google-maps/google-maps-overlay.md) to render some polygons on top of Google Maps. Those polygons come via an [MVTLayer](https://deck.gl/docs/api-reference/geo-layers/mvt-layer) and they all have an attribute called `id`.
I also have a vertically split window with the left side being a list of polygons and the right side the google map where the polygons are drawn.

My use case is the following: When the user hovers their mouse above an element on the list, the polygon with the matching id should be filled with another color. 

What my implementation does is recreate a new MVTLayer each time the hovered list element is changed and rendering that via the GoogleMapsOverlay [setProps](https://github.com/visgl/deck.gl/blob/master/docs/api-reference/google-maps/google-maps-overlay.md#setprops) method. 

Unfortunately, there's a slight delay between the user changing the hovered list element and the map being refreshed. Looking at the javascript profiler traces below you can see that from the half a second it takes to run the `renderLocationCountsData` function (the one that creates the new MVTLayer) almost everything comes from the GoogleMapsOverlay `setProps` method
![image](https://user-images.githubusercontent.com/2301378/97455937-a9a5a400-1938-11eb-9483-be679f44edde.png)
![image](https://user-images.githubusercontent.com/2301378/97456002-b7f3c000-1938-11eb-8e36-4c12b37c08dc.png)

I have tried to reuse the layer only changing the getFillColor property but I get a  `Cannot assign to read only property 'getLineColor'` error

Is there a better way to do this? Can the layer be reused somehow?

Thanks!

**Comment by Pessimistress** [comment]
Have you tried [autoHighlight](https://deck.gl/docs/api-reference/core/layer#autohighlight)?

**Comment by Pessimistress** [comment]
If you are talking about hovering over something outside of deck.gl, see [highlightedFeatureId](https://deck.gl/docs/api-reference/geo-layers/mvt-layer#highlightedfeatureid)

**Comment by ibesora** [comment]
Thanks for the heads up @Pessimistress .
Unfortunately even if using `highlightedFeatureId`, I need to recreate the layer each time because AFAIK there's no way to change the props of an existing layer. Recreating the layer and adding it to the google maps overlay presents no improvement when using `highlightedFeatureId` versus the `getFillColor` function.

**Comment by Pessimistress** [comment]
Can you share your code? Assuming you are calling `setProps({layers: ...})`, creating and updating a layer is very cheap.

**Comment by Pessimistress** [comment]
To clarify, creating a new layer instance does not recreate all the underlying resources. Benchmark for layer constructors run at >1M iterations/second.

See https://deck.gl/docs/developer-guide/using-layers#should-i-be-creating-new-layers-on-every-render

**Comment by ibesora** [comment]
I'll try to create a repo to reproduce but it's not the layer construction per se but adding the layer to the overlay what makes everything slow.

**Comment by Pessimistress** [comment]
That will be very helpful. I just want to clarify that the general statement of "I have to construct a new layer so there's no difference changing one prop over another" is incorrect.

It is true that there is no way to change a layer's props other than constructing a new instance. As I commented before, calling the layer constructor does not have any perf hit on its own.

When you add the layer to Deck by calling `setProps({layers})`, the internal layer state is updated in response to its prop changes. The performance of updating a layer depends on which props are changed. If the  `data` prop of this layer changes, that's the most expensive, because every accessor needs to be reevaluated. Updating an accessor function (using `updateTriggers`) is usually more expensive than updating a constant. An accessor function has to be called for every geometry to populate an attribute array before it's uploaded to the GPU, the cost of which is proportional to the amount of data in this layer. While changing a constant usually means uploading 1-4 numbers as a uniform. You can read about this in https://deck.gl/docs/developer-guide/performance#layer-update-performance .

The `highlightedFeatureId` prop of the MVTLayer is slightly more complicated than a regular constant. Since feature ids are only present on the CPU, the layer does need to iterate through (potentially) all geometries to find the index of the highlighted feature. The index is then uploaded as a uniform. However this is still supposed to be faster than calling `getFillColor` again.

Without seeing your code, it is hard to tell what exactly is slow when you use `highlightedFeatureId`. Turning on [logging](https://deck.gl/docs/developer-guide/debugging#deckgl-logging) may give you better metrics than the Chrome profiler.
