### ISSUE TITLE
Unit test failed - Error: createGLContext on available in the browser.

### ISSUE THREAD

**Issue by ariel-upstream** [visgl/deck.gl#5092]
Hi, 
I'm trying to create a unit test with @testing-library/react on the maps container (Dialog component),
When I'm trying to run the test the error is: 
"Error: createGLContext on available in the browser.
Create your own headless context or use 'createHeadlessContext' from @luma.gl/test-utils" 

Is it possible to test it with this test library?

Thanks.

**Comment by Pessimistress** [comment]
I believe there is a typo in the error message ("only" available in the browser).

WebGL is not supported in Node. If you want to test the DeckGL component under Node you need to install [headless-gl](https://github.com/stackgl/headless-gl) or equivalent, create a WebGLContext, and pass it via the `gl` prop to DeckGL.

**Comment by xap5xap** [comment]
@ariel-upstream. Were you able to fix the problem?

> Hi,
> I'm trying to create a unit test with @testing-library/react on the maps container (Dialog component),
> When I'm trying to run the test the error is:
> "Error: createGLContext on available in the browser.
> Create your own headless context or use 'createHeadlessContext' from @luma.gl/test-utils"
> 
> Is it possible to test it with this test library?
> 
> Thanks.

**Comment by ibgreen** [comment]
deck.gl uses the WebGL API which is not available in Node.js if you are running tests on a React+deck.gl app in Node.js, you can either
- Avoid rendering the `Deck` component in unit tests.
- Run your tests in Chrome headless mode instead of directly under node
- Install headless-gl as the error message indicates.

There is a library [`@deck.gl/test-utils`](https://deck.gl/docs/api-reference/test-utils/overview) that runs unit tests on deck.gl layers.
