### ISSUE TITLE
Edge 16 and extrusions

### ISSUE THREAD

**Issue by dottodot** [visgl/deck.gl#5100]
#### Description
https://deck.gl/examples/geojson-layer-polygons/

When loading extrusions in Edge 16 it doesn't display correctly at all. Is there anything that can be done to overcome this?

![Screenshot 2020-11-05 at 12 35 57](https://user-images.githubusercontent.com/811652/98241890-7f20a000-1f63-11eb-95cc-38356d977cca.png)

**Comment by ibgreen** [comment]
Edge 16 is a very old version of edge. The initial versions of Edge had several tricky WebGL limitiations, so I am not surprised to see that there are issues. 

We would probably accept a PR if someone had a small clean fix, but unless this issue is present on newer Edge versions I suspect that it will not be fixed.

https://en.wikipedia.org/wiki/Microsoft_Edge#Spartan_release_history

**Comment by Pessimistress** [comment]
Edge 16 has an incomplete implementation of WebGL, and also less than 0.01% market share, see https://caniuse.com/usage-table

You may be able to work around some compatibility issues by including 3rd-party polyfill libraries. Adding support for outdated browsers requires significant amount of code that will bloat the size of this library and will be increasingly difficult to maintain. At the moment we do not have plans or resources to test/fix bugs outside of mainstream evergreen browsers.
