### ISSUE TITLE
Is it possible to set texture on a polygon?

### ISSUE THREAD

**Issue by doninpr** [visgl/deck.gl#5130]
Hi. I have PolygonLayer with many simple polygons and I want to set texture on every is it. Is it possible somehow?

PolygonLayer:
![Снимок экрана 2020-11-14 в 18 49 18](https://user-images.githubusercontent.com/23110750/99151253-d97bd800-26aa-11eb-970c-6f3cb3d41395.png)

Texture:
![texture](https://user-images.githubusercontent.com/23110750/99151269-f7493d00-26aa-11eb-8cc9-6c6fa812fe37.png)

**Comment by Pessimistress** [comment]
https://deck.gl/docs/api-reference/extensions/fill-style-extension

**Comment by doninpr** [comment]
> https://deck.gl/docs/api-reference/extensions/fill-style-extension

Thanks. I did it, but image isn't rotate with polygons. Can I fix this somehow?

![Снимок экрана 2020-11-14 в 20 16 42](https://user-images.githubusercontent.com/23110750/99153037-f7e7d080-26b6-11eb-892a-f34cf9b79e3a.png)

**Comment by Pessimistress** [comment]
The pattern generated by FillStyleExtension does not rotate with your polygons because there is no notion of "rotation" in the definition of polygons.

You can use the [SimpleMeshLayer](https://deck.gl/docs/api-reference/mesh-layers/simple-mesh-layer) which allows you to supply your own texture coordinates.

**Comment by doninpr** [comment]
That's works, thanks!
