### ISSUE TITLE
Google base map support with react

### ISSUE THREAD

**Issue by omar-3** [visgl/deck.gl#5443]
#### Target Use case

Google base maps are superb for non-english speaking countries and using openstreetmaps base maps is not adequate in some countries because the coverage is not as good as google.

#### Proposed feature

better google base maps support
 
#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] What’s new update 
  - [ ] Test

**Comment by Pessimistress** [comment]
deck.gl already offers [integration with Google maps](https://deck.gl/docs/api-reference/google-maps/google-maps-overlay). It is not possible to use Google maps as a child of the `DeckGL` React component because Google maps' camera cannot be fully controlled externally. There is nothing preventing you from using deck's `GoogleMapsOverlay` in a React application. If you need help, you can open a thread in discussions and post your code there.
