### ISSUE TITLE
moduleParameters not forwarded from the layers to the luma.gl model

### ISSUE THREAD

**Issue by alexandruandrei91** [visgl/deck.gl#5473]
#### Description
A shader module's `getUniforms` function will get called twice when a layer is drawn:
* First time, with the correct moduleParameters, from here: https://github.com/visgl/deck.gl/blob/55c8fa8f9c22eea3dd9401db580741949ae17f2b/modules/core/src/lib/layer.js#L739
* Second time, starting from here  https://github.com/visgl/deck.gl/blob/55c8fa8f9c22eea3dd9401db580741949ae17f2b/modules/core/src/lib/layer.js#L750
it goes through a layer's draw method, for example in the bitmap layer:
https://github.com/visgl/deck.gl/blob/55c8fa8f9c22eea3dd9401db580741949ae17f2b/modules/layers/src/bitmap-layer/bitmap-layer.js#L203
where model.draw() is called without any arguments, so when luma.gl sets the moduleSettings again here:
https://github.com/visgl/luma.gl/blob/b753c3eb566e57ee0f41afde7ac0c2c67f8f01e2/modules/engine/src/lib/model.js#L291
the modules settings are set again, this time to an empty object.

The first call seems redundant now that updateModuleSettings is called in the draw method of Luma's Model.
The second one would probably work if in every layer's draw method would call something like `model.draw({moduleSettings: opts.moduleParameters})` instead of just `model.draw()`.

#### Expected Behavior
Call module's getUniforms only once per draw, with the correct parameters.

#### Repro Steps
A shader module
```
function getUniforms(opts) {
    console.log(opts);
}

export default {
    name: "decoder",
    fs: `float foo() { return 1.0; }`,
    getUniforms
};
```

For any redraw of a bitmap layer, I get the following output:
```
{autoWrapLongitude: false, viewport: Viewport, mousePosition: {…}, pickingActive: 0, devicePixelRatio: 2, …}autoWrapLongitude: falsecolormap: (...)data: (...)devicePixelRatio: 2image: (...)lightSources: {ambientLight: AmbientLight, directionalLights: Array(2), pointLights: Array(0)}mousePosition: {x: 664, y: 209.16214678551108}pickingActive: 0viewport: Viewport {id: "main", x: 0, y: 0, width: 827, height: 907, …}__proto__: Object
decoder.js:10 {}
decoder.js:10 {autoWrapLongitude: false, viewport: Viewport, mousePosition: {…}, pickingActive: 0, devicePixelRatio: 2, …}autoWrapLongitude: falsecolormap: (...)data: (...)devicePixelRatio: 2image: (...)lightSources: {ambientLight: AmbientLight, directionalLights: Array(2), pointLights: Array(0)}mousePosition: {x: 664, y: 209.16214678551108}pickingActive: 0viewport: Viewport {id: "minimap", x: 662, y: 680, width: 165, height: 227, …}__proto__: Object
decoder.js:10 {}
```

#### Environment
 - Framework Version: deck.gl 8.3.12
 - Browser Version: Chrome 85.0, Firefox 85
 - OS: Windows 10

**Comment by Pessimistress** [comment]
`setModuleParameters` is intended to be called on demand in different contexts. For example, if `autoHighlight` is `true`, it is called on pointer move to just update the picking module uniforms. By design, it is NOT guaranteed to be called only once per redraw. Because of this, in the `getUniforms` callback of a shader module, one should always check that the options they are watching for exist, before updating any uniforms.

The `draw` method of each layer is considered internal to each layer's implementation, and they are not required to conform to any standard. (https://deck.gl/docs/api-reference/core/layer#methods) When you are subsclassing a layer, you are responsible of keeping your own module parameters up to date, not the base layer.

**Comment by alexandruandrei91** [comment]
Ok, thank you for the details! :)
