### ISSUE TITLE
Page crashes with MVT empty binary tiles

### ISSUE THREAD

**Issue by borja-munoz** [visgl/deck.gl#5534]
#### Description
When you try to add an MVT layer using the `binary: true` parameter, the page crashes when there are empty tiles. 

#### Expected Behavior
The page doesn't crash and the empty tiles are processed correctly.

#### Repro Steps
https://codepen.io/borja-munoz/pen/NWbXONv
Open the codepen above and try panning to the west until you reach an area with empty tiles.

#### Environment
 - Framework Version: deck.gl 8.4.8
 - Browser Version: Chrome 88.0.4324.192
 - OS: Mac OS X 10.15.7

#### Logs
No logs but the empty tile request remains in "Pending" status

**Comment by alasarr** [comment]
@padawannn could you check this? the layer shouldn't crash if a worker crash.

**Comment by ibgreen** [comment]
>  the layer shouldn't crash if a worker crash.

And the worker shouldn't crash. Add a test case in loaders.gl?

**Comment by padawannn** [comment]
The problem is with `loaders.gl`, in the `geojson-to-binary.js` file, line 120 `coordLength: Math.max(...coordLengths)`  is returning a `-Infinite` value when features are empty. I don’t know this code well enough to know what it should return in this case. Any help @kylebarron?

Another option could be that geojson-to-binary returns a null value if features are empty but I don't like this option...

**Comment by ibgreen** [comment]
coordinateLength would be zero if no coordinates.

Also we have had issues in other places with using array destructuring: `Math.max(...)` - there is a limit to how many arguments the JS environments can handle. 

Suggest we replace it with a loop and initialize the coordinateLength to 0.

If you put up a PR in loaders.gl I will ensure it gets into next week's patch release (probably Monday)

**Comment by padawannn** [comment]
mmmm if coordinateLength is zero the `drawLayer` layer method returns another error. It seems we have to investigate this further but it is already a bit late in Spain :sweat_smile:

**Comment by padawannn** [comment]
@ibgreen the PR: https://github.com/visgl/loaders.gl/pull/1235

As I said in the previous comment if we initialize the `coordinateLength` to 0 deck gl returns another error. Checking the previous version of loaders.gl `coordinateLength` was initialized to 2. You can see it here https://github.com/visgl/loaders.gl/commit/4ccf15169a134f9bba1a7faf814841f0c0c59060#diff-d06c6e0e237cb5d4bb6705f0b29452c177f9b2a225abdf43340dfb1a4ba7d06eR19

To support the `coordinateLength` zero initialization we should modify the `SolidPolygonLayer`, `PathLayer` and `ScatterplotLayer` so I think that is better to initialize `coordinateLength` to 2 as in the previous version of loader gl.

On the other hand in this case, `Math.max(...)` is not going to be a problem because we're applying this function on a `set` that can only has two values (2 or 3)

**Comment by alasarr** [comment]
Path applied and your codepen is working now.
