### ISSUE TITLE
Defining current limitations of interleaving feature in deck.gl/mapbox API

### ISSUE THREAD

**Issue by tommybru** [visgl/deck.gl#5571]
Hello, I'm looking to integrate the deck.gl/mapbox API into my project, but need some clarification first on the known limitations of the API's interleaving feature.

In [Using deck.gl with a Base Map](https://github.com/visgl/deck.gl/blob/master/docs/get-started/using-with-map.md), it's mentioned interleaving is an experimental feature

> This allows you to interleave deck.gl layers with base map layers, e.g. below text labels or occlude each other correctly in 3D. Be cautious that this feature is experimental: we are working closely with Mapbox to evolve the API.

I see in the [deck.gl/mapbox](https://github.com/visgl/deck.gl/blob/master/docs/api-reference/mapbox/overview.md) page, a few general limitations of the API are listed. 

**However, is there a definitive list of what is experimental about interleaving? What should a developer be cautious about before using the feature?** 

I've been searching through opened and closed issues on this repo, and it's been a good first start. It would be helpful to have more defined limitations of this feature added to the docs .

**Comment by Pessimistress** [comment]
> However, is there a definitive list of what is experimental about interleaving? What should a developer be cautious about before using the feature?

It is experimental because we don't know the full extent of how well it works. Mapbox has many features that we don't regularly use or test, and it is constantly adding new features that this module may not be compatible with. Issues recently brought to our attention include using deck with Mapbox's free camera settings, and synchronization with v2's terrain.
