### ISSUE TITLE
add DECKGL_FILTER_TARGET and DECKGL_FILTER_SOURCE for LineLayer

### ISSUE THREAD

**Issue by farfromrefug** [visgl/deck.gl#5683]
It would be very useful to get something like this:
https://user-images.githubusercontent.com/655344/115456655-b5a55b00-a223-11eb-878d-47d52867aec7.mp4

I can do it by doing:
```
target.y = 0.7 * target.w; // 0.5 - fixed anchor position in clipspace
```
But i need to do it before `getExtrusionOffset`

**Comment by Pessimistress** [comment]
The shader hooks are intended to provide a consistent set of user-facing APIs across most, if not all, layers. `source` and `target` can mean very different things in different layers, and depending on whether a layer's geometry extrudes in screen space or world space, they may be in different coordinate systems too. Since you are trying to inject into the LineLayer particularly, hooks are not necessary. `inject[line] = block` will insert a code block before an arbitrary line in the target shader.

**Comment by farfromrefug** [comment]
@Pessimistress awesome did not know about that line inject feature. awesome thanks
