### ISSUE TITLE
Anti Aliasing not working in a PathLayer when added to existing Mapbox instance using MapboxLayer

### ISSUE THREAD

**Issue by derMart** [visgl/deck.gl#5742]
#### Description
Anti Aliasing not working in a PathLayer when added to existing Mapbox instance using MapboxLayer

#### Expected Behavior
Anti Alias should work in a PathLayer as in the example https://deck.gl/docs/api-reference/layers/path-layer

#### Repro Steps
Add a deck.gl MapboxLayer with a PathLayer into a v1.14.0 maplibre instance (https://github.com/MapLibre/maplibre-gl-js) like so
```
  const layer = new deck.MapboxLayer({
      type: deck.PathLayer,
      id: layerId,
      data: geoJSON.features,
      pickable: false,
      stroked: true,
      filled: false,
      extruded: false,
      getPath: (d) => {
        return d.geometry.coordinates;
      },
      getColor: (d) => {
          return [ 0, 0, 0, 255];
      },
      widthMinPixels: 1,
  });

  map.addLayer(layer);
```
Results in
![Screenshot from 2021-05-07 14-28-24](https://user-images.githubusercontent.com/1069456/117450093-17163b00-af41-11eb-844f-abcac5918dcb.png)

I would not assume maplibre to be the culprit as it is atm just a fork without modifications of mapboxgl.

#### Environment
 - Framework Version: deck.gl 8.4.15
 - Browser Version: Chromium 90 / Firefox 88
 - OS: Ubuntu 20.04

#### Logs
no errors or warnings in the console

**Comment by ibgreen** [comment]
An off the cuff observation is that if you are using the deck.gl/mapbox integration, deck.gl renders into the WebGL1 context created by maplibre, rather than the WebGL2 context that deck.gl would normally create. This does lead to reduced functionality, for instance attribute transitions are not supported, and it could also affect antialiasing, either by maplibre just creating a lower resolution drawing buffer or in other more subtle ways.

I mention this mainly for awareness. A deeper dive into what is happening might uncover something fixable (perhaps maplibre makes some persistent change to the shared WebGL context that affects deck.gl rendering, and it might be possible to temporarily override that setting).

One way to further diagnose this is to see if there is a difference between the mapbox and maplibre renderers. If not it strengthens the WebGL1 hypothesis.

**Comment by Pessimistress** [comment]
You need to create the Map instance with the `antialias:true` [option](https://docs.mapbox.com/mapbox-gl-js/api/map/). I believe it existed prior to the fork.

**Comment by derMart** [comment]
Thank you very much for the fast contributions. The antialias option does the trick. Also thanks for the hint about the WebGL1 context.

**Comment by ibgreen** [comment]
Nice. I assume that just makes maplibre pass the `antialias` property to the WebGL context.

https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/getContext
