### ISSUE TITLE
MVTLayer picking and autoHighlight broken with binary: true

### ISSUE THREAD

**Issue by Pessimistress** [visgl/deck.gl#6006]
#### Description
With `binary: true` point/path features cannot be picked, and autoHighlight mode does not work

#### Expected Behavior
binary mode on/off should behave the same

#### Repro Steps

- Go to https://codepen.io/Pessimistress/pen/oNWGKYv
- Try click on a point (picked object is logged to console) - it is impossible
- Hover over any object - it is not highlighted
- Uncomment `binary: false` and try the above

#### Environment
 - Framework Version: 8.5.0-beta.2
 - Browser Version: Chrome 91.0.4472.114

**Comment by alasarr** [comment]
@felixpalmer I'm working on this

**Comment by alasarr** [comment]
Looking into it I've just realized that for MVT layers with only points autoHighlight works for binary. https://codepen.io/alasarr/pen/oNWoLNq

**Comment by alasarr** [comment]
It looks [binary format for geojson](https://github.com/visgl/loaders.gl/blob/a7b22a70c92f6aa3c21c2999d02ebf8b726c82c9/modules/gis/docs/api-reference/geojson-to-binary.md) don't map feature.id when converting to binary. In the example you provide, the id to highlight is defined as `feature.id` and it's totally right according to the [MVT spec](https://github.com/mapbox/vector-tile-spec/tree/master/2.1#42-features).

When binary mode is enabled, the feature.id is not in the data anymore, so highlight doesn't work.

I had a conversation about this with @kylebarron, but we didn't implement this. We need to define a way to map `feature.id` in the binary format and implement it. 

In the meatime, I suggest to explain in the doc that tiles with `feature.id` are not supported in binary mode with hightlight/picking.

**Comment by alasarr** [comment]
Should we set back binary to false as default until we fix this? thoughts?

**Comment by ibgreen** [comment]
Reverting to `false` could make sense, we do see a lot of usage of / questions around this layer

**Comment by Pessimistress** [comment]
It seems that `glocalFeatureIds` and `featureIds` are just arbitrary unique numbers: https://github.com/visgl/loaders.gl/blob/master/modules/gis/src/lib/geojson-to-binary.ts#L304 There is no reason not to use `feature.id` if present.

On the deck.gl side, picking colors are calculated using `featureIds`: https://github.com/visgl/deck.gl/blob/master/modules/layers/src/geojson-layer/geojson-binary.js#L92 And later interpreted as `globalFeatureId`: https://github.com/visgl/deck.gl/blob/master/modules/geo-layers/src/mvt-layer/mvt-layer.js#L172

**Comment by Pessimistress** [comment]
@kylebarron It's not clear to me what the value of `featureIds` is. If it's just local index per vertex, then it is entirely redundant information (can be derived independently from pathIndices and polygonIndices).

**Comment by ibgreen** [comment]
Not sure if this helps but adding my thoughts:

One consideration is also that binary conversion in loaders.gl is designed to be generic enough to e.g. support arrow table creation, it is not designed to just provide the minimal necessary information needed by deck.gl, though options can of course be provided to avoid generate unnecessary columns.

My understanding is that 
- we split geojson into three binary tables, for points, lines and polygons
- Each table associates each vertex with the local feature index for that table so that object picking can be done independently on each table.
- There is also a globalFeatureId that associates each vertex with the index into the original geojson features array, so that features can be identified in the original data.
- Perhaps another column needs to be generated that contains the user supplied feature ids (which may not be indices and perhaps can be non-numeric/strings?) so that global feature indices can be mapped to user supplied feature ids?

**Comment by Pessimistress** [comment]
Ok. `featureIds` could be useful when retrieving feature properties from the properties array at an index. I would call it `featureIndex` for clarity though. 

I can't think of a scenario where the sequentially generated `globalFeatureIds` are more useful than identifiers provided by the data source.

**Comment by ibgreen** [comment]
> I can't think of a scenario where the sequentially generated globalFeatureIds are more useful than identifiers provided by the data source.

One consideration is whether identifiers provided by the original data source can be represented as 32 bit integers. If they can be 64 bit or strings etc then indirection is useful.

**Comment by kylebarron** [comment]
No disagreement that the binary format could be improved, and happy to have those discussions.



> > I can't think of a scenario where the sequentially generated globalFeatureIds are more useful than identifiers provided by the data source.
> 
> One consideration is whether identifiers provided by the original data source can be represented as 32 bit integers. If they can be 64 bit or strings etc then indirection is useful.

I think 1. the idea was to go with a new unique sequence because GeoJSON doesn't require features to have an `id` property, and 2. as Ib mentions, I believe the `id` [can be a string](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/23789b9bb40246c44938a7130dfc030093160ab4/types/geojson/index.d.ts#L157-L161) as well.

**Comment by alasarr** [comment]
What if we map `feature.id` to binary as a property like `__feature_id__`?

**Comment by Pessimistress** [comment]
If we go with a new column then it will be one array per table, which will be accessed like properties using `featureId`. I still don't see the use of `globalFeatureId`, but as long as there is an option to skip generating them we are good.

**Comment by Pessimistress** [comment]
I agree we should revert the default of `binary` to `false` because of auto highlighting (caused by missing feature ids in loaders.gl). 

However, we do need to fix picking (caused by misinterpreting binary format during picking color generation and pick info handling) before release given that it's a regression from 8.4.

**Comment by alasarr** [comment]
Added a PR for the first one

**Comment by Pessimistress** [comment]
Correction: `feature.id` is uint64

https://github.com/mapbox/vector-tile-spec/blob/ab55f2bd7b8c0af5d9a845e4bb0b133811ce3ccf/2.1/vector_tile.proto#L32

**Comment by felixpalmer** [comment]
I've been looking at fixing the autohighlighting in deck.gl and have noticed that there is an issue with using `feature.id` as a unique id as (per spec) the `id` should only be unique within a MVT Layer. Thus a single MVT tile can have (and generally does) multiple features with the same id. This means that when the data is converted into binary format the `fields` array has duplicate values in it.

In fact playing around with the original codepen example posted, I see that autohighlighting is broken even in the non-binary case, in that sometimes hovering over a feature doesn't highlight it, but instead highlights another one elsewhere (or none at all), so this problem also occurs in the non-binary case.

This happens because the `MVTLayer.getHighlightedObjectIndex()` method uses `hoveredFeatureId` to look up a feature from the data (in both the binary and non-binary case), and the first matching feature is returned which may not be from the correct layer.

Any thoughts on how best to fix this? One approach would be add `hoverFeatureLayerName` to the `state` and improve the `getHighlightedObjectIndex()` method to use this when searching for the feature.

**Comment by Pessimistress** [comment]
Matching both feature id and layer name is definitely going to make it better. Eventually, we can't fix problems in the tiles, and maybe we should provide an opt-out for the user if unique ids do not exist in the source data.

The binary version of `getHighlightedObjectIndex` is even more problematic because it's just returning the first geometry type that has anything at the given index: https://github.com/visgl/deck.gl/blob/d67688e3f71a37e2f021dde6681bb1516bebac2b/modules/geo-layers/src/mvt-layer/mvt-layer.js#L219

**Comment by Pessimistress** [comment]
Fixed in 8.5.4.
