### ISSUE TITLE
Tile3DLayer(with i3s) is not close to the map ground

### ISSUE THREAD

**Issue by Bowen7** [visgl/deck.gl#6060]
#### Description

Tile3DLayer(with i3s) is not close to the map ground

![image](https://user-images.githubusercontent.com/27432981/128139567-bcefbd94-2586-4088-9e67-3b9f920fd278.png)

#### Repro Steps
[CodeSandbox](https://codesandbox.io/s/keen-sun-fly4c?file=/src/App.js)

the same display on the loaders.gl website [loaders.gl examples](https://loaders.gl/examples/i3s)

#### Environment
 - Framework Version: deck.gl 8.5.2
 - Browser Version: Chrome 92.0.4515.107
 - OS: Mac OS X 10.15.7

**Comment by ibgreen** [comment]
This is because 3D tilesets typically contain actual 3D coordinates, where the z coordinate is measured from mean sea level, rather than a relative offset from the "ground".

This means that 3D tiles in general do not mix well with flat 2D maps. 

How to deal with this depends on the application. As one option, as an alternative to a flat basemap, deck.gl provides a terrain layer, loaders.gl has an experimental example.

@dryabinin-actionengine @belom88 it might be nice to add a switch to the tile examples to show the terrain layer...

**Comment by Bowen7** [comment]
Thank you for clearing that up
