### ISSUE TITLE
[Question + Feature Request] Using Marker vs. React Components in IconLayer

### ISSUE THREAD

**Issue by jyjyj** [visgl/deck.gl#6078]
Hi,

Referencing my discussion topic below, I would like to use custom components for my `React` Components instead, due to both legacy code as well as forward scalability by allowing future use of custom (specifically) `Material-UI` icons in my map.

I am currently thinking of either sticking with `<IconLayer>` which isn't very flexible with the icons (I wouldn't want to re-generate the SVGs for the potentially numerous types of icons that I might use in the future) but is an innate part of `deck.gl`, vs. using individual `<Marker>`s as in [https://deck.gl/docs/api-reference/react/deckgl#contextprovider](here) with `ContextProvider`. I believe I haven't seen this raised anywhere else, so may I know what are the pros and cons of either? I assume for best compatibility that I should use as much of the container (my overaching <DeckGL> component) as possible.

If `<Marker>` is the easier way to customise icons at the moment, is it possible to raise a feature request for `<IconLayer>` to support React components like Material-UI's icons?

### Discussed in https://github.com/visgl/deck.gl/discussions/6068

<div type='discussions-op-text'>

<sup>Originally posted by **jyjyj** August  6, 2021</sup>
As mentioned in the title, can I use the [Material UI icon imports](https://material-ui.com/components/material-icons/) in the IconLayer? I would like to leverage the performance of `deck.gl` by using `IconLayer` rather than using individual `<Marker>`s, which is what I did with `react-map-gl` previously. 

Alternatively, can I use a Material UI icon or general React component? My goal is to display icons with dynamically-generated counts.

Thanks!</div>

**Comment by Pessimistress** [comment]
I have already informed you in #6069 that Discussions is the proper place to ask questions. Please do not keep opening new issues on the same topic.

WebGL and React work in fundamentally different ways. The reason that WebGL is more performant is precisely because it is not rendered from a DOM tree. You seem to be implying that if the markers are rendered dynamically, then it'll use less resources than pre-generating them. This is false in the context of WebGL. If you want performance, then you need to give up some of the convenience that React grants you. In the Discussion thread I have linked you to documentation on how to use Material icons the recommended way.

I would also like to point out that while deck.gl is designed with a reactive model, it is NOT dependent on React. The core engine and layers work perfectly in vanilla JS, and there are many developers using it with Angular and Vue. The `@deck.gl/react` module offers a React wrapper around the core. We do not consider build in React-specific features into the core itself.

**Comment by Pessimistress** [comment]
One more note: you seem to have a specific use case in mind that the examples in the documentation do not address. I encourage you to share your use case with an open-ended discussion ("how do I achieve this?") rather than forcing your way through a preconceived solution ("I want to solve this with x and why is x not supported?")

**Comment by jyjyj** [comment]
Hi @Pessimistress I did not mean to be stubborn and open multiple issues regarding the same thing. As shown in my title, this was intended to be both a question and potentially a feature request, which I believe is accepted here in the issues thread. Noted on the independency from React. Apologies that I may not be too familiar with the best practices here. Thanks.
