### ISSUE TITLE
GeoJsonLayer switch between 2D and 3D rendering

### ISSUE THREAD

**Issue by crnismrk** [visgl/deck.gl#6409]
#### Target Use case
I use GeoJsonLayer in a map application. User can switch from 2D to 3D and vice versa. All geometries have z coordinate that represent height and in most cases it is different from 0. When user changes to 2D geometries stay in the air.
I need GeoJsonLayer that will interpret z coordinate as zero when used in 2D and interpret z coordinate as it is when in 3D.

#### Proposed feature
Add GeoJsonLayer  prop that differentiate rendering in 2D and rendering in 3D. Ideal solution is to pass this prop value to a shader and there implement necessary calculations (changes) 

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] What’s new update 
  - [ ] Test

**Comment by Pessimistress** [comment]
You can use the [modelMatrix](https://deck.gl/docs/api-reference/core/layer#modelmatrix) prop to remove z:

```js
import {Matrix4} from 'math.gl';

new GeoJsonLayer({
  modelMatrix: new Matrix4().scale([1, 1, 0])
})
```

**Comment by crnismrk** [comment]
Well, that solves my problem for now.
But I noticed that extruded polygons are now flattened in 2D. What I really want is that they stay extruded but that their base moves to height = 0 in 2D. In 3D I want them their base to be at actual height (determined by z coordinate in geometry). That way I don't need to go trough GeoJSON features and change z coordinates every time one switches from 3D to 2D and vice versa.
Thank you for your answer. If you have further suggestions please write.

**Comment by Pessimistress** [comment]
You can also set the `positionFormat` prop to `'XY'` (default `'XYZ'`) for it to ignore the altitude.

Note that this flag is only used by PolygonLayer and PathLayer when they initially process the geometries, so to switch between 2D and 3D you need to manually trigger a data update:

```js
new GeoJsonLayer({
  positionFormat,
  updateTriggers: {
    all: [positionFormat]
  }
})
```

This is less efficient than `modelMatrix` because instead of sending 16 numbers to the GPU you are recalculating all attributes. But better than iterating through the features yourself.
