### ISSUE TITLE
RTD not updated

### ISSUE THREAD

**Issue by michaelaye** [visgl/deck.gl#6503]
#### Link

https://deckgl.readthedocs.io/en/latest/layer.html

#### Description
Just a note that RTD doesn't seem to be up to date?
For example https://deckgl.readthedocs.io/en/latest/layer.html has a broken link to deck.gl layers catalog that seems to be fixed in the main branch.

**Comment by kylebarron** [comment]
cc @ajduberstein do you know how the pydeck docs are currently published? Should we consider automating the pydeck docs publishing on CI?

**Comment by ibgreen** [comment]
There is https://github.com/UnfoldedInc/pydeck

**Comment by kylebarron** [comment]
Both pydeck.gl and deckgl.readthedocs.io currently show the latest version in the changelog as `0.6.1`. Since then `0.6.2`, `0.7.0` and `0.7.1` have been published.

The only feature of https://github.com/UnfoldedInc/pydeck is aliasing the `readthedocs` url to `pydeck.gl`, no? It's irrelevant to the actual publishing of the documentation I believe?

We have a CI script to publish the JS docs [here](https://github.com/visgl/deck.gl/blob/master/.github/workflows/website.yml); we could do something similar for the pydeck docs.

**Comment by ajduberstein** [comment]
It’s a quick task to update the RTD docs to the latest version of pydeck.

I’m in favor of the CI hook for updating docs—RTD has that built in. I’ll see if I can get it added.

pydeck.gl currently points to the GitHub pages web page under Unfolded’s repositories. It’s likely less maintenance going forward to consolidate on RTD and would be great if the .gl domain could point there. Open to discussion on the point.

**Comment by ajduberstein** [comment]
@michaellaye Thank you for reporting the issue. I think this is resolved. Feel free to re-open if not.
