### ISSUE TITLE
[Feat] Simplify Mapbox integration API

### ISSUE THREAD

**Issue by Pessimistress** [visgl/deck.gl#6773]
### Target Use Case

There are currently 3 paths to use the `@deck.gl/mapbox` module as documented by https://deck.gl/docs/api-reference/mapbox/overview:

- Construct a `MapboxLayer` directly (a `Deck` instance is created under the hood when the layer is added to the map)
-  (PureJS) Create a `Map` first, then a `Deck` instance using the map's GL context, then construct a `MapboxLayer` from a layer id from the deck
- (React) Mount a `DeckGL` component first, then a `ReactMapGL` component using deck's GL context, then construct a `MapboxLayer` from a layer id from the deck

The complexity of supporting multiple scenarios has generated numerous bugs since the module's launch due to inconsistency of behavior and general confusion among users.

I'm proposing a transition to a new API that uses Deck as a Mapbox custom control (see [IControl](https://docs.mapbox.com/mapbox-gl-js/api/markers/#icontrol)). This will offer multiple benefits:

- Align the APIs between Mapbox and Google Maps integrations
- Hides some of the implementation detail regarding GL context configuration that tends to confuse the users.
- Eliminates the hacky React use case. `react-map-gl` already offers an interface to wrap third-party controls as React components.
- Allows react-map-gl v7 to use deck.gl with other native controls
- Allow deck.gl to be used with early forks of `mapbox-gl` that do not support custom layers.

### Proposal

https://github.com/visgl/deck.gl/pull/6738#issuecomment-1060379748

> Great to see that the interface is now the same as the GoogleMapsOverlay, will simplify integrations where both can be supported, or swapped out.
>
> One thing I wonder (as this is for future consideration, not this PR) is how we deal with the interleaved layers vs separate canvas overlay. Right now `MapboxOverlay` will always render into a separate overlaid canvas, while `GoogleMapsOverlay` will share a canvas (ignoring the legacy raster maps code path). I wonder if this could be made more consistent, either by:
>
> Switching `MapboxOverlay` to share the canvas by using a `MapboxLayer` under the hood providing a prop in both overlays, e.g. `interleaved` to let the user decide

**Comment by chrisgervang** [comment]
If the support for interleaved canvases with Mapbox/Maplibre-gl-js is removed, then hubble.gl will no longer function with these basemaps since it captures video frames of one canvas.

It's not entirely clear to me if that is the proposal, but @felixpalmer mentioned in the PR that MapboxOverlay doesn't interleave yet.

**Comment by Pessimistress** [comment]
A possible API to support this is to call it **<del>MapboxOverlay</del> MapboxControl** (as it is an implementation of mapbox's `IControl`). You can use it as an overlay:

```js
const deck= new MapboxControl({
  layers: [
    new ScatterplotLayer({
      id: 'points',
      data: ...
    })
  ]
});

map.addControl(deck)
```

Or you can use it interleaved, in which case it does not render any DOM component of its own:

```js
const deck= new MapboxControl({
  interleaved: true,
  layers: [
    new ScatterplotLayer({
      id: 'points',
      beforeId: 'water-labels',
      data: ...
    })
  ]
});

map.addControl(deck)
```

**Comment by felixpalmer** [comment]
That is what I had in mind regarding the `interleaved` prop.

I think there is a bigger question here on whether we try to design the API so that it is closely aligned with the base map libraries (Google/Mapbox etc) or if we try to have a concept of an `AbstractOverlay` that works the same way irrespective of the provider. E.g. it is a bit unfortunate that for Mapbox we do `map.addControl(deck)` and for Google `overlay.setMap(map)`.

My view is that it should be as simple as possible to switch between basemaps, ideally allowing users to replace the class name and some access tokens and not have to worry about the API. With this in mind I would align on `overlay.setMap(map)`.

**Comment by zakjan** [comment]
`interleaved` prop name might be a too general term because there are more specifics to consider. How about `overlay`, with opposite meaning? `interleaved = true` == `overlay = false`

[Leaflet integration](https://github.com/zakjan/deck.gl-leaflet) is non-interleaved by the definition that it creates a separate canvas, but still supports interleaving, because the deck layer can be inserted in between of other Leaflet layers in the DOM. After the common API is decided and implemented, I'll update the Leaflet integration to match it.

I want to look at potential OpenLayers integration as well. OpenLayers is mainly Canvas-based, but has some overlay WebGL layers already ([points](https://github.com/openlayers/openlayers/pull/9994), [tiles](https://github.com/openlayers/openlayers/pull/12008)).

> Right now MapboxOverlay will always render into a separate overlaid canvas, while GoogleMapsOverlay will share a canvas (ignoring the legacy raster maps code path).

If both interleaved and non-interleaved modes are possible, better to keep them both. There are animation performance issues ([Mapbox](https://github.com/mapbox/mapbox-gl-js/issues/8159), [Maplibre](https://github.com/maplibre/maplibre-gl-js/issues/96)) or missing WebGL2 support ([Mapbox](https://github.com/mapbox/mapbox-gl-js/issues/8581), [ArcGIS](https://github.com/visgl/deck.gl/issues/5005), Google Maps, Maplibre).

**Comment by Pessimistress** [comment]
I feel that trying to unify the interface will create more maintenance trouble down the road.

The way the Mapbox/Google integrations work right now conforms with each library's respective conventions. This makes it easy for new developers who are familiar with one base map provider to get started with deck.gl. If they have ideas to improve the integration, they can be encouraged to contribute it, with no risk of breaking some unspoken of "API alignment" that is only apparent when you use multiple integration modules.

It might also be too optimistic to try to design a pattern based on two data points. ArcGIS requires custom implementations to extend base classes, while Mapbox/Google only requires implementing an interface. This is the reason behind why the [overlaid](https://deck.gl/docs/api-reference/arcgis/deck-layer) and [context sharing](https://deck.gl/docs/api-reference/arcgis/deck-renderer) versions of `@deck.gl/arcgis` use completely different code paths. You can see that the deck layer/renderer is added to a "view", not a "map".

There still are a lot of subtle differences between Mapbox and Google Maps. Google does not have the notion of layer order in the context sharing case, but allow you to insert the overlay canvas in between different "panes". While it would be a great world where you can just switch base maps, I do not wish to create the illusion that every integration works the same. That isn't honest.

**Comment by ibgreen** [comment]
Another observation is that to date our approach has been that we (i.e. the vis.gl projects) have done the majority of the work in implementing base mao integrations and we have taken on the entire maintenance burden for these. 

However, as deck.gl matures and adoption continues to increase, we have gradually been seeing base map providers more actively supporting / funding / enableing deck.gl integrations. 

Might we (vis.gl community) be able to take some initiative here? E.g. could we define and document one or two preferred "integration models" for base map suppliers to consider when they evolve their APIs? I.e. we could state what stating what APIs they should build to integrate for deck.gl, rather than just trying to work with whatever "random" APIs that base map provider may have built in the past for other use cases.

**Comment by chrisgervang** [comment]
I agree with @Pessimistress that prioritizing ease of integration over maintainability likely isn't going to yield a great result at this point.

I appreciate @ibgreen's suggestion to set the spec that would work best for vis.gl. If we can articulate positive impacts following the vis.gl spec has, then it will likely be easier for them to garner support.

Some examples of current pain points I have experienced include inconsistent behavior between vis.gl and mapbox for internal canvas sizing (tied to device pixel ratio), viewport boundaries (tied to external canvas size), projections and view types (first person / orthographic), and layer blending (mapbox changes GL options during draws and doesn't revert them back). Consistency across behaviors like these are important for a successful basemap integration.

**Comment by felixpalmer** [comment]
Related: I have put up a PR adding support for the non-interleaved mode in the Google Overlay: https://github.com/visgl/deck.gl/pull/6804

With regards to naming, I prefer `interleaved` over `overlay` as it is a bit strange to have an `GoogleMapsOverlay` class with an `overlay` prop. Open to other suggestions.

I take the points regarding maintainability, perhaps it was too hopeful that we could find a common interface for all the different providers. I like @ibgreen 's suggestion with having a way of "papering-over" the differences approach in a separate repo/project - even if this means that such an `OmniMapOverlay` (for want of a better name) might only support a subset of the basemap functions.
