### ISSUE TITLE
[Bug] SPATIAL INDEX  - Maximum call slack size excedeed in h3

### ISSUE THREAD

**Issue by AnaDiaz85** [visgl/deck.gl#7102]
### Description

I am getting an error apparently when I using low zooms with h3.

### Flavors

- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxLayer
- [ ] GoogleMapsOverlay
- [x] CartoLayer
- [ ] DeckLayer/DeckRenderer for ArcGIS

### Expected Behavior

It should work without returning any error

### Steps to Reproduce

1. Run the following query from builder:
```
select `carto-un`.carto.H3_FROMGEOGPOINT(geom,4) as h3, avg(point_order) as avg_point_order
from `carto-dev-data.public.points_500k` 
group by h3
```
2.Move around the map, style the layer

Actually, I am not sure how to reproduce it, it seems related with h3 layer with a very low zoom

### Environment

Framework version: `8.8.0-beta`.`latest`
Browser: Chrome
OS: MacBook Pro Version 12.4

**Comment by Pessimistress** [comment]
CARTO builder is not part of deck.gl.

And why is "ArcGIS" selected in the issue?

**Comment by AnaDiaz85** [comment]
> CARTO builder is not part of deck.gl.
> 
> And why is "ArcGIS" selected in the issue?

Hi @Pessimistress , sorry, I deselected "ArcGIS", it was a mistake from my side.
About the issue, it is not just happening in Builder, thats why I opened this issue.

**Comment by felixpalmer** [comment]
There was some miscommunication here. The bug was originally reported in Builder, but then a repro scenario was found which worked just with CartoLayer. I asked @AnaDiaz85 to move that here, but I meant the CartoLayer bug.

@AnaDiaz85 in general when creating issues on the deck repo the bug should be reproducible using just deck.gl code - if it requires Builder or other CARTO products it should be handled on our internal system
