### ISSUE TITLE
[Doc] Updated example for using react-map-gl Components with DeckGL

### ISSUE THREAD

**Issue by callumfrance** [visgl/deck.gl#7129]
### Link

https://deck.gl/docs/whats-new#use-react-map-gl-components-with-deckgl

### Description

Hey guys,

I am trying to use the [`react-map-gl`](https://visgl.github.io/react-map-gl/) controls (e.g. [`FullScreenControl`](https://visgl.github.io/react-map-gl/docs/api-reference/fullscreen-control)) with a `DeckGL` component in React-TypeScript land.

The documentation makes reference to `MapContext` in `react-map-gl`, however this has since been changed out for `useMap()` and `useControl()` hooks [as documented here](https://visgl.github.io/react-map-gl/docs/upgrade-guide#module-exports), and as pointed out in this previous issue https://github.com/visgl/deck.gl/issues/6285#issuecomment-1049836085 .

---

Here is what it looks like without using a DeckGL solution and just using react-map-gl components inside of DeckGL -

![Screen Shot 2022-07-08 at 12 30 17 pm](https://user-images.githubusercontent.com/13757101/177917187-b65b2a19-a0ef-4c51-b9b4-1a68058bcf92.png)

As you can see, there is a component in the DOM that covers the controls on the top-right.
This means these controls are not interactive.

Here is that code which clearly does not have working controls -

```ts
import { HexagonLayer } from '@deck.gl/aggregation-layers/typed';
import { DeckGL } from '@deck.gl/react/typed';
import {
  Map,
  ScaleControl,
  FullscreenControl,
  NavigationControl,
  AttributionControl,
} from 'react-map-gl';
import 'mapbox-gl/dist/mapbox-gl.css';

const initialViewState = {
  longitude: 8.525,
  latitude: 47.394,
  zoom: 12,
  pitch: 40.5,
};

export interface Props {
  shownLayers: Array<HexagonLayer>;
}

export const MappyBoy = ({ shownLayers }: Props) => {
  return (
    <DeckGL layers={shownLayers} initialViewState={initialViewState} controller>
      <Map
        attributionControl={false}
        mapStyle="mapbox://styles/mapbox/light-v10"
        mapboxAccessToken=<TOKEN_HERE>
      >
        <NavigationControl position="top-right" />
        <FullscreenControl position="top-right" />
        <AttributionControl position="bottom-right" />
        <ScaleControl position="bottom-right" />
      </Map>
    </DeckGL>
  );
};

```

**Comment by Pessimistress** [comment]
https://deck.gl/docs/developer-guide/base-maps/using-with-mapbox#react-map-gl

**Comment by callumfrance** [comment]
Cool,

Using the example in https://deck.gl/docs/api-reference/mapbox/mapbox-overlay#using-with-react-map-gl 

I was able to update my code to get it working as follows

```ts
import { HexagonLayer } from '@deck.gl/aggregation-layers/typed';
import { MapboxOverlay, MapboxOverlayProps } from '@deck.gl/mapbox/typed';
import {
  Map,
  ScaleControl,
  FullscreenControl,
  NavigationControl,
  AttributionControl,
  useControl,
} from 'react-map-gl';
import 'mapbox-gl/dist/mapbox-gl.css';

function DeckGLOverlay(props: MapboxOverlayProps) {
  const overlay = useControl<MapboxOverlay>(() => new MapboxOverlay(props));
  overlay.setProps(props);
  return null;
}

// ...

export const MappyBoy = ({ shownLayers }: Props) => {

  // ...

  return(
    <Box style={{ position: 'relative' }} fill>
      <Map
        attributionControl={false}
        initialViewState={initialViewState}
        mapStyle="mapbox://styles/mapbox/light-v10"
        mapboxAccessToken=""
      >
        <DeckGLOverlay layers={shownLayers} />
        <NavigationControl position="top-right" />
        <FullscreenControl position="top-right" />
        <AttributionControl position="bottom-right" />
        <ScaleControl position="bottom-right" />
      </Map>
    </Box>
   );
};
```

**Comment by rullymartanto** [comment]
which version it is? I use version  7.0.15 and  7.0.20 get  this issue "Cannot destructure property 'mapLib' of 'object null' as it is null."

**Comment by rullymartanto** [comment]
so using like old doesn't support?
`  <DeckGL
        height="100%"
        width="100%"
        viewState={viewport}
        controller={true}>
        <Map
          mapStyle="mapbox://styles/mapbox/dark-v9"
          mapboxAccessToken={MAPBOX_KEY}
          style={{ zIndex: 999 }}
        >
          <NavigationControl position="top-left" />
        </Map>
</DeckGL>
`

**Comment by jonenst** [comment]
Hi @Pessimistress , your docs improvements in #7124 in are clearly welcome, especially the very clear sentence
"To use deck.gl with react-map-gl v7's controls, you must use [MapboxOverlay](https://deck.gl/docs/api-reference/mapbox/mapbox-overlay#using-with-react-map-gl)."

However, they contrast with the first paragraph of the page:
"[Using the Deck canvas as a overlay on top of the Mapbox map, and Deck as the root element.] is the most tested and robust use case, as you can find in all the [examples on this website](https://deck.gl/examples/website). It supports all the features of Deck."
"[Using the Deck canvas as a overlay on top of the Mapbox map] is favorable if you need to use other mapbox-gl controls and plugins in addition to deck.gl."

As a result I was confused as to why the recommended (root deck mode) mode just didn't work for basic features like NavigationControl with recent versions of react-map-gl.

Maybe you could also rework that section ? I see several possibilities
* Adding "with old react-map-gl versions" to  "It supports all the features of Deck."
* Adding "and if you want to use the latest version of react-map-gl to "MapboxOverlay is favorable if .."
* recommending MapBoxOverlay instead of Root Deck first because it works with the latest react-map-gl version and has been used for a while now ? (note: what about react-map-gl with maplibre or mapbox 1? does it work transparently ?)
* explaining a bit more how long and why there's this apparent paradox between the most robust form of using deck not supporting recent react-map-gl versions ?


Additionally, maybe update the only example with controls (examples/get-started/react/mapbox/app.jsx )to use a more recent version than     `"react-map-gl": "^5.3.0"`

These are just ideas and suggestions, feel free to only pick up the ones you like.
Cheers,
Jon

PS: also commenting here since google results for this page come out first before the official docs and hopefully this clarifies some things for people

**Comment by Pessimistress** [comment]
@jonenst Using DeckGL as the root element supports all the features of **deck.gl**, not the features of **react-map-gl** or **mapbox-gl**. The limitations of MapboxOverlay are listed on its own documentation page.

I am open to suggestions for improving the docs. Please open a new issue as we do not actively monitor closed issues and PRs.

**Comment by jonenst** [comment]
@Pessimistress Sure, thanks
