### ISSUE TITLE
[Feat] RFC: Filter by category in DataFilterExtension

### ISSUE THREAD

**Issue by felixpalmer** [visgl/deck.gl#7827]
### Target Use Case

deck.gl includes the [DataFilterExtension](https://deck.gl/docs/api-reference/extensions/data-filter-extension) which allows GPU filtering of a dataset via an accessor:

```js
new GeoJsonLayer({
  ...
  extensions: [new DataFilterExtension({filterSize: 1})]
  getFilterValue: f => f.properties.timeOfDay,  // in seconds
  filterRange: [43200, 46800],  // 12:00 - 13:00
});
```

A limitation of this approach that is that it only works for filters which can be represented as a continuous numeric range. There is no way to construct a filter which filters based on discrete categories.

### Proposal

A new accessor, `getFilterCategory` and prop, `filterCategories`, are added to the extension which allows the user to filter by a set of discrete values.

```js
new GeoJsonLayer({
  ...
  extensions: [new DataFilterExtension()]
  getFilterCategory: f => f.properties.country,
  filterCategories: ['spain', 'usa']
});
```

The above example will only display features where the country property matches any one of the values in the `filterCategories` array.

## Implementation

Consider first the implementation where each category is represented as an unsigned integer. We can then form a mask from these values by taking each value (n) and setting the nth mask bit to 1. So `filterCategories: [1, 3, 7] => 100 0101 => 69`. Thus we can encode these 3 categories as the value of 69 which is passed to shader as a uniform. The shader then decodes the mask and compares it to the attribute value that is populated via `getFilterCategory`.

### Maximum number of categories

In WebGL we can represent uniforms are represented as 32 bit integer which are 32 bit values. Thus we can exactly represent integers in the range `0 -> 2 ** 32` which gives support for up to 32 categories. 

If this uniform is declared as `vec4` we get 4 times as many categories: 128.

### String categories

To support strings as categories, the extension maintains a mapping between string and integers internally and only passes the integer values to the GPU. This is transparent to the user.

### Compound category filters

In order to filter by category on multiple properties, an array can be returned like with the `getFilterValue` accessor:

```js
new GeoJsonLayer({
  getFilterCategory: f => [f.properties.country, f.properties.type],
  filterCategories: [['spain', 'usa'], ['school', 'airport']]
});
```

In order to specify the number of category filters, the constructor is extended to include the `categorySize` parameter, which is analagous to `filterSize`. The maximum value is 4

### Usage with filterRange

As the category filtering has its own dedicated accessor & filter definition it can be used together with the existing filtering by numerical range.

### Interaction with other props

As the category filtering is discrete in nature, `filterTransformSize` & `filterTransformColor` are not supported

**Comment by ibgreen** [comment]
This is a very cool idea. Some quick thoughts:

GPU
- I would use integer GPU math for this, not try to repurpose floats. It requires WebGL2 but that should be OK. That gives you access to all 32 bits and 128 categories for the `uvec4`

Regarding the mapping of categorical values to numbers:
- You explain the comparison bitmask , but not explicitly how the categorical column is converted to attribute. I don't think we do create GPU attributes for string columns today?
- Is the mapping (dictionary) of strings to numbers supplied, or is it auto calculated?
- If auto-calculated, are there any complications when the data table is defined by an iterator and not all values are available apriori?
- There some complications around similar dictionaries in e.g. apache arrow, for instance when streaming batches, that seem like they might apply to our case as well as we are talking about binary columnar representations in both cases.

High-level
- Given that we keep systematically extending our filter system, is it worth having a design meeting and taking a look at the overall design of filtering and building it as an extension?
- I.e. is the current extension architecture fit for purpose as we add this and perhaps more additional functionality?
- I have a hunch that we might be able organize this around a columnar table abstraction, making it a major design feature of the library, rather than putting all the code in a huge but optional deck,gl "extension" where it can seem like an iceberg of hidden complexity.

**Comment by alexwing** [comment]
**Temporary solution for categorical filtering in deck.gl**

I've found a temporary solution to implement categorical filtering in deck.gl using the DataFilterExtension. My approach relies on using a hash function to convert categories into unique numbers, which are then used for filtering.

Firstly, in the `getFilterValue` accessor, I use a hash function to convert categories into unique numbers. In my case, I'm filtering by continent, so my `getFilterValue` function looks like this:

```javascript
getFilterValue: (f) => hashString(continent === "All" ? "All" : f.properties.continent),
```

Here, `continent` is a variable determining which continent I'm filtering. If I'm filtering for all continents, I pass "All" to the hash function; otherwise, I pass the corresponding continent from the entity's properties.

Next, in the `filterRange` parameter, I set the filtering range using the hash values of the categories. In my case, it would look like this:

```javascript
filterRange: [hashString(continent), hashString(continent)],
```

The `hashString` function I use to generate the hash values is as follows:

```javascript
export function hashString(str: string): number {
  var hash = 0;
  if (str.length === 0) return hash;
  for (var i = 0; i < str.length; i++) {
    var char = str.charCodeAt(i);
    hash = (hash << 5) - hash + char;
    hash = hash & hash; // Convert to 32-bit integer
  }
  return hash;
}
```

This function takes a string as input and returns a unique number representing that string. I use this approach to map each category to a unique value that can then be used for filtering.

It's important to note that this solution is temporary and has some limitations. For example, the hash function may generate collisions, meaning two different strings may generate the same hash value. However, for now, this solution has allowed me to effectively implement categorical filtering in deck.gl.

If anyone has any suggestions for improving this solution or if there's a more elegant way to achieve categorical filtering in deck.gl, I'd love to hear it!

**Comment by felixpalmer** [comment]
@alexwing this feature was merged into master just last week, you can try it in `9.0.0-beta.4`. FWIW, I don't think your approach works in all cases, it only allows you to filter for all continents or just one, it won't let you independently filter cities by the country they are in, if you have say 50

**Comment by alexwing** [comment]
> @alexwing this feature was merged into master just last week, you can try it in `9.0.0-beta.4`. FWIW, I don't think your approach works in all cases, it only allows you to filter for all continents or just one, it won't let you independently filter cities by the country they are in, if you have say 50

Thanks for pointing that out. You're correct; my approach was limited. I've used alpha values to hide elements in other projects as a workaround. I'll give the beta version a try. Appreciate the development of this feature!
