### ISSUE TITLE
[Bug] Google 3D tiles not as sharp/detailed as in Cesium

### ISSUE THREAD

**Issue by joedjc** [visgl/deck.gl#7955]
### Description

Comparing similar locations in Deck GL vs Cesium, the 3D tiles don't appear as accurate/sharp at higher levels of details.

For example, here on the Eiffel Tower, some areas appear blurry and not lined up.

Possibly the tiles are not always being loaded at their highest detail? The issue repeats each time the page loads

Here are some screenshots to compare:

<img width="832" alt="Screenshot 2023-06-18 at 12 21 40" src="https://github.com/visgl/deck.gl/assets/13920398/f5dc5e4e-d30d-4b59-9cdd-a57a8a1d42a6">

<img width="703" alt="Screenshot 2023-06-18 at 12 23 47" src="https://github.com/visgl/deck.gl/assets/13920398/a1d40444-929f-49a9-9626-96fc44971c19">

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [X] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

Map tiles should display at same quality in Cesium or Google maps itself.

### Steps to Reproduce

Visit the Eiffel Tower (south-east face) in Deck GL, and in Cesium (can be viewed here: https://3d-tiles.web.app/#orbit)

Compare the quality at high zoom levels.

### Environment

- Framework version: 8.8.0
- Browser: Version 113.0.5672.126
- OS: MacOS 13.3.1

**Comment by radoslavirha** [comment]
Hi @joedjc I think it may be related to the zoom level of the map and 3D tile LOD calculation, as the max value is at true 0 and not on the terrain itself. I'm not sure if this is true, but I've seen similar behaviour on 3D tiles with higher elevation.

**Comment by joedjc** [comment]
@radoslavirha ok yeah that could be a factor, though from what I can tell other tiles nearby at similar heights appear to load at a higher detail level - such as adjacent areas of the tower.

**Comment by radoslavirha** [comment]
It's hard to say because I don't know how the LOD is calculated, but I've seen something similar with some datasets with altitudes above 500m. In other 3D viewers it was much more detailed. I didn't have time to investigate though.

**Comment by felixpalmer** [comment]
Could you try lowering the screen space error? https://github.com/CartoDB/tiles3d-demo/blob/master/layers/google-3d.js#L34

**Comment by Beilinson** [comment]
I've also encountered similar issues with some cesium ion datasets available, and similarly changing the screen space error made no difference at higher zoom levels.

**Comment by felixpalmer** [comment]
It would be helpful if somebody could analyze the data loaded by deck&Cesium for rendering the exact same view to help ascertain whether the issue here is the tile traversal or rendering. I.e. I would like to understand better if the blurry texture is due to a missing tile or if deck has the tile, but for some reason is rendering a lower resolution tile instead

**Comment by RELNO** [comment]
to add to what @radoslavirha said, when analyzing the LOD of 3D tiles in deck, the max level is 19 (via `tileset3d.options.onTraversalComplete = (selectedTiles) => {selectedTiles.forEach((tile) => {console.log(tile)))}` )

**Comment by felixpalmer** [comment]
@RELNO do you know what it is in Cesium?

@akre54 to continue our discussion from Slack, it would be useful if somebody could investigate if there is a difference in the data being loaded. So basically, load the exact same view in deck&Cesium and compare the tiles that are being fetched.

In order to minimize noise you can load just a subset of the tiles, by specifying a different root tile to the `data` prop, e.g. `https://tile.googleapis.com/v1/3dtiles/datasets/CgA/files/UlRPVEYuYnVsa21ldGFkYXRhLnBsYW5ldG9pZD1lYXJ0aCxidWxrX21ldGFkYXRhX2Vwb2NoPTk1MCxwYXRoPTIxNTM3MzQxNjE2MzczNjQsY2FjaGVfdmVyc2lvbj02.json?session=CPH34cHNiv3-pwE` (you will likely need your own session parameter). This can be found by inspecting the network requests the client makes and filtering by by "json" to find the tilesets. Perhaps this also works in Cesium.

An ideal repro scenario would be a jsfiddle for deck and one for Cesium which load the same location with a visible difference in quality, along with a comparison of the data fetched.

**Comment by ibgreen** [comment]
If I read this right, it seems that there is a level of detail that loaders.gl won't access no matter how much we zoom in or adjust the thresholds. That seems strange.

Regardless of how we want to fix this, we would benefit from good test tools to help us understand what is going on. 

@belom88 Would the [I3S explorer](https://i3s.loaders.gl) be of any help in examining a 3D tiles tileset being loaded? 
- Even though it focuses on I3S I assume it still works on 3D tiles? 
- Does it have any tools for inspecting anything traversal related information? Can we zoom in on the finest tile and see in the inspect if they have children?

**Comment by RELNO** [comment]
@ibgreen not a tool per se, but running this inside the layer should log the zoom level of current tile(s). With a local state, it's possible to see it won't (as of now) exceed 19. 

```
 new Tile3DLayer({
      id: "google-3d-tiles",
      data: TILESET_URL,
      loadOptions: {
        fetch: { headers: { "X-GOOG-API-KEY": GOOGLE_MAPS_API_KEY } },
      },
      operation: "terrain+draw",
    onTilesetLoad: (tileset3d) => {
      console.log("tileset3d", tileset3d);
      tileset3d.options.onTraversalComplete = (selectedTiles) => {
        selectedTiles.forEach((tile) => {
          const tileSelectionDepth = "current depth is:" + tile?._selectionDepth;
          console.log(tileSelectionDepth)
        });
    };
    },
    })
```

**Comment by ibgreen** [comment]
Are we also able to see if those tiles contain information about additional children that are not being loaded? I.e. are we not loading those tiles because of a bug, or because we are not aware that they exist?

**Comment by RELNO** [comment]
As far as I saw, the `children` objects were empty in the most zoomed-in level:
```
      onTilesetLoad: (tileset3d) => {
        tileset3d.options.onTraversalComplete = (selectedTiles) => {
          selectedTiles.forEach((tile) => {
            tile?._selectionDepth > 18 && console.log(tile.children);
          });
          return selectedTiles;
        };
      },
```
Which yields empty arrays. In other words, `loaders` seems not to get/post deeper levels.
<img width="836" alt="Screenshot 2023-06-26 at 10 21 06 AM" src="https://github.com/visgl/deck.gl/assets/14296774/a64524b4-9905-4937-bedf-c3bdd2763590">

**Comment by ibgreen** [comment]
The full hierarchy of tiles is normally present in the top-level tileset JSON files. Those could be inspected to see if they include the information about the missing tiles. the tile header of each tile should have been populated from them.

@belom88 is there any hierarchical information stored directly in the GLBs in the new 3D tiles format?

**Comment by felixpalmer** [comment]
Thanks for the info @RELNO. Are you able to report what Cesium does this case? Is it loading tiles of level 20+?

**Comment by felixpalmer** [comment]
I've checked in Cesium, by modifying https://sandcastle.cesium.com/?src=Google%20Photorealistic%203D%20Tiles.html with 

```javascript
tileset.tileLoad.addEventListener(tile => {
   console.log(tile._depth);
});
```

Loading in the Eiffel tower I see values as high as 31. `tile._selectionDepth` is also present but is always 0

**Comment by Beilinson** [comment]
I would like to add on (maybe this is related) that I've noticed that load times in cesium are much faster for the same tile set, especially when quickly transitioning from low to high zoom. It looks as if deck tries to load the tiles at all zoom levels during that zoom in, while cesium either discards unneeded requests or only requests the needed zoom tiles

**Comment by RELNO** [comment]
Have had similar experience @Beilinson, though could not observe a clear pattern: sometimes tiles load fast for parts of the viewport and then stall, other times is simply slow all around.

**Comment by chrisgervang** [comment]
> My feeling is that the data is getting loaded, but for some reason deck chooses to render low resolution data, which obscures high res tiles.

I suspect the tiles are all loaded, but lower resolution tiles are occluding higher resolution tiles. I've seen improved quality when close up by tuning `filterSubLayer` based on @felixpalmer's exploration in a slack discussion.

```js
class CustomTile3DLayer extends Tile3DLayer {
  static layerName = 'CustomTile3DLayer'

  filterSubLayer({ layer, viewport }: FilterContext) {
    // Do not show tiles which are many layers too low in resolution (avoids artifacts)
    const { lodMetricValue, screenSpaceError } = layer.props.tile;

    // viewport.zoom doesn't change FirstPersonView. What to use instead?
    if (viewport instanceof FirstPersonViewport) {
      return (
        screenSpaceError < 50 || lodMetricValue < 2
      )
    }
    
    // MapViewport
    const lodZoom = 22 - Math.log2(lodMetricValue)
    return lodZoom > viewport.zoom
  }
}
```

**Comment by ibgreen** [comment]
@chrisgervang Thanks for the continued investigation. My hunch is that this is a good lead that could save time for someone who wanted to make a pass at improving the 3D tiles traversal algorithm.

**Comment by felixpalmer** [comment]
Some progress reading the tealeves from the Tile3D tree....

I managed to hack the [I3S debug app](https://github.com/visgl/loaders.gl/blob/master/examples/website/i3s/src/app-debug.tsx) to use the Google tileset (only works for me on `3.4-release` branch to inspect the tiles.

Zooming in on the blurry section of the Eiffel tower we can inspect the tile being rendered:

<img width="917" alt="Screenshot 2023-08-14 at 12 24 30" src="https://github.com/visgl/deck.gl/assets/453755/34b33f19-b00b-4817-bb47-e8ee001ce672">

Notice how the first element in the `childrenIds` is blank. By noting the tileId and setting the following conditional breakpoint at line 104 in [`tileset-traverser.ts`](https://github.com/visgl/loaders.gl/blob/master/modules/tiles/src/tileset/tileset-traverser.ts#L104)

```javascript
tile.header.id && tile.header.id.includes('UlRPVEYubm9kZWRhdGEucGxhbmV0b2lkPWVhcnRoLG5vZGVfZGF0YV9lcG9jaD05MjQscGF0aD0zMDYwNDA2MDcxNjM2MjYwNTcxLGNhY2hlX3ZlcnNpb249Ng')
```

we can inspect the children of this tile and find the child that is showing up blank in the debug UI. The content of the `tile.children[1].header` is:

```json
{
  "boundingVolume": {
    "box": [
      4201050.045345581,
      168347.37439069795,
      4780263.117237955,
      0.13321411461359245,
      0.005341448498421844,
      0.15260804708503847,
      -0.016237503250639322,
      0.4049584339731688,
      1.8689095638682094e-17,
      -0.15248551727694332,
      -0.00611416845469093,
      0.13332115887714388
    ]
  },
  "geometricError": 1e+100,
  "extras": {
    "comment": "path = '30604060716362605710'"
  },
  "lodMetricType": "geometricError",
  "lodMetricValue": 1e+100,
  "type": "empty"
}
```

This tile is of type `"empty"` unlike the other `"scenegraph"` tiles in the `children` array. By manually removing (`tile.children.splice(1, 1)`) this child and then removing the breakpoint and letting the traversal continue, the blurry rendering glitch is fixed:

<img width="849" alt="Screenshot 2023-08-14 at 12 36 16" src="https://github.com/visgl/deck.gl/assets/453755/70f40737-2951-4f69-9644-2c062e3abad8">


So why does this empty tile break traversal? While it is present the `updateAndPushChildren` method always returns `false`, which sets `shouldRefine` to `false` and thus `stoppedRefining` to `true`. As such [`selectTile`](https://github.com/visgl/loaders.gl/blob/master/modules/tiles/src/tileset/tileset-traverser.ts#L141) is executed with the blurry tile, and the children are not visible.

The reason `updateAndPushChildren` always returns `false` is due to [`executeEmptyTraversal` returning `false`](https://github.com/visgl/loaders.gl/blob/master/modules/tiles/src/tileset/tileset-traverser.ts#L203) when invoked with the empty tile. 

`executeEmptyTraversal()` [assumes](https://github.com/visgl/loaders.gl/blob/master/modules/tiles/src/tileset/tileset-traverser.ts#L354-L366) that it will be able to either traverse the children of the given tile or that the tile will have content. Neither will ever be true for an empty childless tile and thus this method will forever return `false`, blocking the tile refinement.

Modifying the logic resolves the rendering glitch:

```
if (traverse) { 
  ...
} else if (!tile.contentAvailable && !tile.hasEmptyContent) {
  allDescendantsLoaded = false;
}
```

**Comment by akre54** [comment]
Great detective work, @felixpalmer . Let me or @chrisgervang know if we can help test any patch. Thanks for looking into this!

**Comment by felixpalmer** [comment]
@akre54 I've merged into master & 3.4 in loaders.gl so once the new version is published it would great if you could test. I have tested with a local build and the results are good

**Comment by felixpalmer** [comment]
Fixed in loaders.gl 3.4.11

**Comment by Kris-B** [comment]
Is this issue really fixed ?

On the example for Google 3D Title (https://deck.gl/examples/google-3d-tiles), the details are ok with this zoom level:

![image](https://github.com/user-attachments/assets/27f1ff2f-97ac-47f2-ab75-8b53f612ee33)

but, when I zoom in, details are lost :

![image](https://github.com/user-attachments/assets/e8d1b2d6-9277-4d3e-a1ed-8a9640523e06)

any idea ?
