### ISSUE TITLE
[Feat] Improvements in CARTO Module API for v9

### ISSUE THREAD

**Issue by alasarr** [visgl/deck.gl#8047]
### Target Use Case

@deck.gl/carto was created in version [v8.3 (Oct 12, 2020)](https://deck.gl/docs/whats-new#deckgl-v83), since then the platform has evolved a lot. The following major changes have been addressed progressively:

- When it was created we only supported Query Layers and MVT format. Now we support Queries, Tables, Tilesets, Rasters, H3, and Quadbin.
- We only supported PostgreSQL, today we support: PostgreSQL + BigQuery + Snowflake + Redshift + Databricks.
- Parametrized queries were also introduced for better control of queries in public applications.
- In the new version of deck.gl we have Typescript. 

As the CARTO platform has grown, the `CartoLayer` has been used to implement a wide variety of functions, with the result that it can be unclear to developers what is going on:
- The primitive layer used for rendering is obscured from the user, e.g if you set `geoColumn=geom` it will use a GeoJsonLayer, if `geoColumn=h3|quadbin` H3HexagonLayer or QuadbinLayer will be used. 
- Props are dependent on the layer type being used, e.g. aggregationExp has no meaning for non-spatial index datasets. QueryParameters are only available for Query layers.
- No easy way for the developer to use a custom layer for rendering.
- No types to enforce correct options.

We are working right now in v9, so I think it's a great time to address those changes. Especially because v9 will expose types at the package roots.

### Proposal

Rather than having a generalistic `CartoLayer`,  we should provide the user with a set of loaders which allow them to easily pull data from the CARTO platform and use those with an explicit layer.

Typescript will work nicely with an explicit layer and it will help the user understand how it works under the hood.

### Rendering geometry data (tileset/queries/tables)

```javascript
import CartoSQLLoader, CartoSQLLoaderOptions, CartoTileLayer, SPATIAL_DATA_TYPE from '@deck.gl/carto';

// Type definition for load options, e.g. allows enforcing
// value of spatialDataType
const cartoLoadOptions: CartoSQLLoaderOptions = {
  accessToken: 'XXXX',
  apiBaseUrl: 'https://gcp-us-east1.api.carto.com', // optional
  connectionName: 'bigquery',
  spatialDataColumn: 'geom',
  spatialDataType: SPATIAL_DATA_TYPE.GEOM
}

// CartoTileLayer is a lightly modified MVTLayer, aside from
// using a different data format, all the props are the same
const layer = new CartoTileLayer({
  data: 'select * from `cartobq.testtables.mytable`',
  loaders: [CartoSQLLoader],
  loadOptions: {carto: cartoLoadOptions}
});
```

### Loading data without Layer

```javascript
import load from '@loaders.gl/core';

// Can avoid 'await' using load().then(function(data) {...}
const data = await load(
  'select * from `cartobq.testtables.mytable`',
  CartoSQLLoader, {carto: cartoLoadOptions});
```

### Rendering spatial index data

```javascript 
import CartoSpatialTileLoader, CartoSpatialTileLoaderOptions, H3TileLayer from '@deck.gl/carto';

const cartoLoadOptions: CartoSpatialTileLoaderOptions = {
  accessToken: 'XXXX',
  connectionName: 'bigquery',
  spatialDataColumn: 'h3',
  spatialDataType: SPATIAL_DATA_TYPE.H3,
  aggregationExp: 'AVG(population) as population'
}

const layer = new H3TileLayer({
  data: 'cartobq.testtables.myh3table',
  
  // (optional) defaults to CartoSpatialTileLoader
  // loaders: [CartoSpatialTileLoader],   
  loadOptions: {carto: cartoLoadOptions}
});
```

**Comment by alasarr** [comment]
Opening a RFC PR will also help to define the full api

**Comment by ibgreen** [comment]
Certainly excited to see proposals. 

Just be aware that right now, loaders.gl allows loader to implement `parse` but not `load`.

`load` essentially calls the `fetchFile` function and then delegates to the selected loaders `parse()` function which know how to `parse` the resulting data (whether binary or text) into JS structures..

So this wouldn't work:
```typescript
// Can avoid 'await' using load().then(function(data) {...}
const data = await load(
  'select * from `cartobq.testtables.mytable`',
  CartoSQLLoader, {carto: cartoLoadOptions});
```

You'd need an intermediary function like `runCartoQuery` that runs the query and loads it:

```typescript
// Can avoid 'await' using load().then(function(data) {...}
const data = await load(
  runCartoQuery('select * from `cartobq.testtables.mytable`', cartoQueryOptions),
  CartoSQLLoader, {carto: cartoLoadOptions});
```

**Comment by alasarr** [comment]
In a talk with @felixpalmer we have agreed to continue the proposal based on the following table with the mapping between loaders and layers that CARTO module could potentially use.

Thanks a lot for the tip @ibgreen, we will include it in the RFC.

Source Type | Loader | Layer
-- | -- | --
table | CartoTableLoader | CartoTileLayer
tileset | CartoTilesetLoader | CartoTileLayer
query | CartoQueryLoader | CartoTileLayer
table | CartoTableLoader | CartoTileLayer
tileset | CartoTilesetLoader | CartoTileLayer
query | CartoQueryLoader | CartoTileLayer
table | CartoH3TableLoader | CartoH3TileLayer
query | CartoH3QueryLoader | CartoH3TileLayer
tileset | CartoH3TilesetLoader | CartoH3TileLayer
table | CartoQuadbinTableLoader | CartoQuadbinTileLayer
query | CartoQuadbinQueryLoader | CartoQuadbinTileLayer
tileset | CartoQuadbinTilesetLoader | CartoQuadbinTileLayer
raster | CartoRasterLoader | CartoRasterTileLayer


Next step is create an RFC and continue the discussion there 💪

**Comment by alasarr** [comment]
Do we really need the Tile suffix in the layer name? 🤔

**Comment by felixpalmer** [comment]
@alasarr as @ibgreen writes a fundamental limitation we will hit here is that loaders.gl expects a single URL which it then fetches and only then we can apply custom code in the `parse()` method. All our API requests are in fact two requests:

- Map instantiation (constructs URL from props, fetches from API and reads data URL)
- Data fetch (fetches data URL and parses response, which will always be a TileJSON)

I was hoping that the above could somehow be encapsulated into a loader, but I don't think that is possible.

Given that of the two requests above only the map instantiation actually performs the mapping of options (`aggregationExp`, `sourceName` etc), perhaps the way to go is something like:

```javascript
import CartoSpatiallDatasource, CartoSpatialDatasourceOptions, H3TileLayer from '@deck.gl/carto';

const cartoLoadOptions: CartoSpatialDatasourceOptions = {
  accessToken: 'XXXX',
  connectionName: 'bigquery',
  spatialDataColumn: 'h3',
  spatialDataType: SPATIAL_DATA_TYPE.H3,
  aggregationExp: 'AVG(population) as population'
}

// Returns Promise which fetches from the map instantiation endpoint,
// resolving to the URL from which to fetch the TileJSON
const data = CartoSpatiallDatasource(cartoLoadOptions);

const layer = new H3TileLayer({
  data
});
```

**Comment by alasarr** [comment]
mmm... In the first view, I like the concept of having a source object as we don't split part of the configuration in the layer and part in the layer.

**Comment by ibgreen** [comment]
There are some options. 
- For the Cesium ION loader which requires some ping/pong with the server we added a `preloadI()` method to the loader.
- The loader system allows the user to pass in a custom fetch function as an option so that is something you could play with.

However for the `preload` approach in particular it really feels like an ugly hack that keeps coming back to bite us. It is not in a shape where I would like to see additional loaders using it, unless we take the time to really define the mechanism and solve its problems.

Just a thought: Perhaps a better approach might be to think about query based data sources and if we can come up with a generalization for those (rather than try to shoehorn queries into a URL centric loader system)? Such a system could then be extended to integrate with other SQL sources, not just CARTO.

**Comment by ibgreen** [comment]
Probably not relevant but just FYO the `load` function doesn't just accept URLs, it also accepts `ArrayBuffer`, `Blob`, `File`, `Response` etc, basically any form of already loaded data. In this case it just forwards that data to `parse()`. Only when it receives a string URL does it try to fetch it before handing it to `parse()`

**Comment by ibgreen** [comment]
So one problem I have with this is that loaders have not been designed to target a specific service, with the exception of systems like 3d tiles and i3s where the behavior of the service is prescribed by the standard.

However there is currently a wave of interest in adding support for various geospatial web services, including some recent code that does implement URL formation: The `WMSService` class, which is an instance of an `ImageService` which can be passed to the experimental deck.gl WMSLayer. Another implementation of this interface could be written for e.g. the ArcGIS ImageServer.

Generally loaders.gl has favored a stateless model, where loaders work on standard URLs or objects and return plain JavaScript structures (not classes) that are easily serialized, transferred between threads etc.

There have been multiple suggestions to wrap both output data and input in classes to provide some extra convenience to users but mostly I have resisted as I feel it would make the library more arbitrarily opinionated and less reusable and composable.

For geospatial services (OGC, ArcGIS etc), and the new generation of new "cloud-optimized" formats like pmtiles, COG, COPC, multi step loading is necessary. 

Not yet sure where that will end up. The dream would certainly be to handle these with light weight composable abstractions rather than heavy class hierarchies forcing applications to buy into our abstractions.

As this evolves there may be a natural place to fit query loading into this system.

**Comment by ibgreen** [comment]
```
const ImgurLoader = {
  urlTemplate: 'https://imgur.com/gallery/{id}?res={resolution}' // could also be a function
  ...
}
```

Note that functions can't be transferred when running loaders on threads. Did some experiments with splitting up loading on the main thread and the parsing on the worker thread but the logic became overwhelmingly complex. 

So while offering function-valued parameters can provide a flexible customization fallback, the general preference is to keep options as plain javascript data. 

Of course with the service concept that would not be a problem as the URLs would be formed in the service class on the main thread and not in the invoked loaders. 

Side note, is there a pattern of image services that take a `res` parameter or is this more a one-off or incomplete example?

**Comment by felixpalmer** [comment]
> Side note, is there a pattern of image services that take a `res` parameter or is this more a one-off or incomplete example?

I just made this up to have a simple loader which took multiple parameters
