### ISSUE TITLE
feat(pydeck): support v9 in bindings

### ISSUE THREAD

**Issue by Jesus89** [visgl/deck.gl#8227]
### Target Use Case

Provide a new version of pydeck and pydeck-carto that uses deck.gl version 9.

### Proposal

Adapt the changes of v9 to the following packages:

**pydeck**

Test pydeck with deck.gl v9 and prepare the required changes.

Release new beta version 0.9.0b1.

**pydeck-carto**

Test pydeck-carto with deck.gl v9 and prepare the required changes.

Release new beta version 0.2.0b1.

RFC: https://github.com/visgl/deck.gl/blob/master/dev-docs/RFCs/v8.0/carto-v9-rfc.md
Tracker: https://github.com/visgl/deck.gl/issues/8148

**Comment by donmccurdy** [comment]
@Jesus89 I believe all the required changes are now implemented by https://github.com/visgl/deck.gl/pull/8577, but I did want to mention a few differences in the PR, compared to what you've described above:

1. I've included support for H3TileLayer and QuadbinTileLayer. I'm not sure what the `get_hexagon` and `get_quadbin` accessors mean in your comment above. Have I missed something in the PR?
2. The PR uses the syntax `access_token=carto_auth.get_access_token()` instead of `access_token=pdkc.get_access_token(carto_auth)`, hopefully that is fine and expected. :)
