### ISSUE TITLE
[Bug] Error converting picking info from binary to geojson in new v9 VectorTileLayer

### ISSUE THREAD

**Issue by juandjara** [visgl/deck.gl#8443]
### Description

Hello team!
I'm building a map application with the new deck.gl v9 beta and I'm experiencing a blocking bug when trying to add hover effects to a VectorTileLayer. I'm working with world borders data from natural earth, which contains very big and complicated polygons and I want to highlight the polygon borders when hovering over them, but after a few times interacting with the map using this effect, the canvas completely blocks and there is no way to resume it.

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [X] CartoLayer
- [ ] ArcGIS

(initially discovered on a react project, tested on stackblitz without react)

### Expected Behavior

The behaviour I'm expecting is to be able to create hover effects on tiled polygon layers with big amount of data

### Steps to Reproduce

I have created a minimal reproduction on StackBlitz where you can check this behaviour. In this link you can see the public dataset I'm consuming and the code I'm using to build the map

https://stackblitz.com/edit/github-k4fd48?file=index.ts

To reproduce the bug, move the map to trigger some tile loading and hover rapidly between countries (polygons) and in a few seconds the map will be frozen completely and imposible to move

### Environment

- Framework version: deck.gl@9.0.0-alpha.7
- Browser: Firefox 121.0.1 (also tried on Chromium 120.0.6099.234 with same result)
- OS: Mac OS Ventura 13.5

### Logs

![Captura de pantalla 2024-01-22 a las 11 02 13](https://github.com/visgl/deck.gl/assets/6652814/54962f27-3cdd-456f-a260-5c8638a0ca8b)

**Comment by donmccurdy** [comment]
Notes and observations while debugging:

1. The application is crashing because feature IDs are reported as 'picked' which cannot be found on the source layer in `getPickingInfo -> binaryToGeojson -> getSingleFeature`.
2. I recorded the 'picked' feature IDs by layer, and whether they failed or succeeded. Table below.
    ![picking_results](https://github.com/visgl/deck.gl/assets/1848368/99fca1de-ed2b-450a-ba2c-a4fd1076881f)
    In some cases the picked IDs are clearly valid, in other case I can't tell.
3. Picking failures do not occur until after the first time we pan or zoom the map after page refresh. If we avoid pan/zoom, picking works as expected without errors.
4. Output of the picking buffer appears reasonable, when I force the picking parameter on when drawing to canvas.[^1] While the map below appears to be black, these are RGB values representing 1-2 digit integers as measured in a color meter.
    <details>
      <summary>screenshot 🗺️</summary>
      <img src="https://github.com/visgl/deck.gl/assets/1848368/f702a26e-3846-491c-b799-c4f8a5f3a5aa">
    </details>
5. I never observe picking failures when moving the mouse among contiguous features, e.g. between countries in Europe. Only when I move the mouse into an area without features, e.g. the Mediterranean, do I see errors.

My hunch, based on all of the above, is that perhaps the picking pass is being drawn into a buffer that hasn't been cleared. I'll continue investigating along these lines tomorrow.


[^1]: By [overriding the `isActive` parameter](https://github.com/visgl/deck.gl/blob/940da34c207c9a980ad7162dd7b700b1dfd127d7/modules/core/src/lib/layer.ts#L1065-L1067) in `layer.ts`.

**Comment by felixpalmer** [comment]
@donmccurdy the lack of a clear operation seems very likely. While fixing the postprocessing code I came across exactly that, the ping-pong buffers being used to render the effects we not being cleared. Sometimes the issue was that the clear command [ignored the fact that rendering](https://github.com/visgl/deck.gl/pull/8471/files#diff-b673b2716aa075bd53b5233e65d06b2aab4199a95293288d1a20a4099dadc58aR52) was being performed to a framebuffer, sometimes it was [simply missing](https://github.com/visgl/deck.gl/pull/8471/files#diff-c3cbad55ae15018bea81712fe9467de37237b99ef51c3e4c4fa987f40400a6c0R87)

In fact, you may want to try merging my branch into yours as it may already contain the fix :)

**Comment by donmccurdy** [comment]
Ah they were very similar issues clearing buffers, yes! The post-processing PR doesn't contain the exact fix I needed here, but it's essentially the same thing — I've opened a PR in #8475.
