### ISSUE TITLE
[Bug] Performance regression when navigating and perfoming fly actions on a map

### ISSUE THREAD

**Issue by juandjara** [visgl/deck.gl#8458]
### Description

Based on a previous issue #8443 and with the help of some colleagues, I've been able to discover a consistent performance regression in **the last version of deck.gl** `v9.0.0-beta.1`.

When navigating on the map, on navigating to a certain bbox you can see a clear jitter in the transition. I've created a reproductible case with the minimal amount of code posible. It contains no React APIs, and **no basemaps**.

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [X] CartoLayer
- [ ] ArcGIS

### Expected Behavior

A minimal example with only one `VectorTileLayer` and no basemap should respond quickly to mouse interactions and fly to commands

### Steps to Reproduce

Open this stackblitz reproduction: https://stackblitz.com/edit/github-k4fd48-vwctf1?file=index.ts,index.html

1. navigate around the map
2. click the big fly button in the top right corner
3. observe the jitter

### Environment

- Framework version: deck.gl@9.0.0-alpha.7
- Browser: Firefox 121.0.1 (also tried on Chromium 120.0.6099.234 with same result)
- OS: Mac OS Ventura 13.5

### Logs

<details>

<summary>LOG OUTPUT</summary>

![Captura de pantalla 2024-01-29 a las 16 36 09](https://github.com/visgl/deck.gl/assets/6652814/3bb84635-9598-42f5-9d4c-f265bc808e22)
![Captura de pantalla 2024-01-29 a las 16 36 40](https://github.com/visgl/deck.gl/assets/6652814/28dfb7ed-29c0-47cf-ae87-e22c15f1d690)
![Captura de pantalla 2024-01-29 a las 16 37 01](https://github.com/visgl/deck.gl/assets/6652814/dcbeef6e-f5ef-4c95-ae9e-bc9feff352a6)

The luma.gl warnings in the last screenshot keep repeating themselves, so there is like 300 of them on a single render

</details>

**Comment by donmccurdy** [comment]
Hi @juandjara! On my laptop, it seems like the performance regression is happening only when the browser's Developer Tools are open. If I close Developer Tools entirely, so that the JavaScript Console is not shown, the navigation is much smoother. So it might be that this issue is caused by the number of warnings being logged — do you mind confirming that performance is also improved on your computer, when Developer Tools are closed?

Thanks!

**Comment by juandjara** [comment]
Hi Don! I just checked the stackblitz link with devtools closed and behaviour looks the same to me

**Comment by donmccurdy** [comment]
@juandjara thanks! By "the same" I assume you mean there is still a performance problem? I've pushed this code to a standalone demo, using the latest beta-3:

https://deckgl-v9-perf-test.vercel.app/

The tiles load very slowly (10-15s) but that is unrelated. Once the tiles load, the map seems smoothly interactive for me. Panning around a bit and then pressing the "Fly" button also seems to move the camera smoothly:

[perf_test.webm](https://github.com/visgl/deck.gl/assets/1848368/4792dfad-67b9-4573-9fe4-e9f1937223cd)

Do you see something different than this, and if so could you record a screen capture of it? Since I'm having trouble reproducing the issue, it might also be helpful to know if you see similar issues with just a basemap and without the VectorTileLayer. Thanks!

**Comment by juandjara** [comment]
Hi Don!
Thanks for your research!

I could not exactly confirm if the performance issues were due to tiles loading slowly or the map transitions being janky but I will send you a recording so we can further investigate this.


https://github.com/visgl/deck.gl/assets/6652814/5e7128fe-a223-412f-97f6-7f5e33ecebb9



Also, I think the global public tileset used in the example you deployed is now deleted. I have changed in the stackblitz. You can now use this one instead `tileset_glo_admin0countries_v1` (it is a tileset not a table)

**Comment by donmccurdy** [comment]
Thanks! I think I have a lead on the problem now, with a profile running during the 'fly' operation:

![Screenshot 2024-02-20 at 3 55 52 PM](https://github.com/visgl/deck.gl/assets/1848368/d9b97763-bd98-464b-9ffd-821f34fd5511)

The callstacks above end up at calls to getShaderParameter...

![Screenshot 2024-02-20 at 3 56 08 PM](https://github.com/visgl/deck.gl/assets/1848368/fd734cf5-348c-4659-9056-25929d05e0d5)

... which suggests that we might be compiling shaders for each new tile? I'm guessing that's not expected, and will keep looking into that.

**Comment by donmccurdy** [comment]
Proposed fix:

- https://github.com/visgl/luma.gl/pull/1950
