### ISSUE TITLE
[Bug] getPickingInfo doesn't work with Map/Set data

### ISSUE THREAD

**Issue by iamenrique** [visgl/deck.gl#8814]
### Description

When using a [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) as an IconLayer data, the picking info doesn't fill the `object` field in the tooltip/click `PickingInfo`. On the other hand, using an Array works.

This affects not only the `onClick` and `getTooltip` events, but also the `Deck.pickObjects` function.

I'm using the deck.gl npm package @ 9.0.5

### Flavors

- [ ] Script tag
- [ ] React
- [ ] Python/Jupyter notebook
- [ ] MapboxOverlay
- [ ] GoogleMapsOverlay
- [ ] CartoLayer
- [ ] ArcGIS

### Expected Behavior

According to the [Layer data docs](https://deck.gl/docs/api-reference/core/layer#data), `data` can be either Array or Map. Thus, I expect the info of the clicked/hovered elements are provided with no difference.

### Steps to Reproduce

https://codepen.io/enrique-nidiro/pen/BaEvPQo

### Environment

- Framework version: 9.0.5
- Browser: Chrome 124.0.6367.61 (Official Build) (arm64)
- OS: Mac OS Sonoma 14.0 (M1 Max)

### Logs

Looks like not-Array object are ignored by the flow:
![image](https://github.com/visgl/deck.gl/assets/7999776/72de57b1-a792-4a27-9886-03e4aa34d4e6)

**Comment by Pessimistress** [comment]
`PickingInfo.object` is only populated if data is an array.

There is no guarantee it will be populated as layer data can also be a non-iterable.

While the layer could find the object at `PickingInfo.index` in a Map/Set, it's not going to be performant. It is important for the picking logic to be simple because it is called at every animation frame when the pointer is moving. If you need the picked object regularly you should consider converting your Map/Set to an array anyways.

**Comment by iamenrique** [comment]
That's why I thought. And makes sense, totally. However, I think pointing this out somewhere in the documentation could help understanding this. 

Is it possible to contribute with these kind of doc changes/proposal?

Thanks!

**Comment by iamenrique** [comment]
@Pessimistress Hope it helps!
